### ISSUE TITLE
error in official faster rcnn-voc example. hybrid_forward()

### ISSUE THREAD

**Issue by sodadi** [dmlc/gluon-cv#1002]
Hi,
I am using the https://gluon-cv.mxnet.io/build/examples_detection/demo_faster_rcnn.html script on the voc2007 data.

after the data load, I get the following error while the script reads the train_data:

  _File "<ipython-input-1-684c53df0030>", line 1, in <module>
    runfile('C:/IPA/Projects/trademarkDetection/datasetcreation/frcnn/train_faster_rcnn.py', wdir='C:/IPA/Projects/trademarkDetection/datasetcreation/frcnn', post_mortem=True)

  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 827, in runfile
    execfile(filename, namespace)

  File "C:\ProgramData\Anaconda3\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 110, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "C:/IPA/Projects/trademarkDetection/datasetcreation/frcnn/train_faster_rcnn.py", line 527, in <module>
    train(net, train_data, val_data, eval_metric, batch_size, ctx, args)

  File "C:/IPA/Projects/trademarkDetection/datasetcreation/frcnn/train_faster_rcnn.py", line 429, in train
    executor.put(data)

  File "C:\ProgramData\Anaconda3\lib\site-packages\gluoncv\utils\parallel.py", line 119, in put
    out = self._parallizable.forward_backward(x)

  File "C:/IPA/Projects/trademarkDetection/datasetcreation/frcnn/train_faster_rcnn.py", line 287, in forward_backward
    box_targets, box_masks, _ = net(data, gt_box, gt_label)

  File "C:\ProgramData\Anaconda3\lib\site-packages\mxnet\gluon\block.py", line 540, in __call__
    out = self.forward(*args)

  File "C:\ProgramData\Anaconda3\lib\site-packages\mxnet\gluon\block.py", line 907, in forward
    return self._call_cached_op(x, *args)

  File "C:\ProgramData\Anaconda3\lib\site-packages\mxnet\gluon\block.py", line 797, in _call_cached_op
    self._build_cache(*args)

  File "C:\ProgramData\Anaconda3\lib\site-packages\mxnet\gluon\block.py", line 749, in _build_cache
    data, out = self._get_graph(*args)

  File "C:\ProgramData\Anaconda3\lib\site-packages\mxnet\gluon\block.py", line 741, in _get_graph
    out = self.hybrid_forward(symbol, *grouped_inputs, **params)  # pylint: disable=no-value-for-parameter_

**TypeError: hybrid_forward() takes from 3 to 4 positional arguments but 5 were given**

Can someone help me with this?
mxnet version - mxnet-cu92==1.4.1

**Comment by qiudi0127** [comment]
I alse met this error, can anyone help solve it?  Thanks!

**Comment by zhreshold** [comment]
@Jerryzcn Seems like the latest frcnn refactor caused the error, can you take a look?

**Comment by hotplot** [comment]
I also have this issue when running the [end-to-end Faster R-CNN training script](https://gluon-cv.mxnet.io/_downloads/b4f246ad140f6fdb320f4e350864798f/train_faster_rcnn.py) from the [Faster R-CNN VOC tutorial](https://gluon-cv.mxnet.io/build/examples_detection/train_faster_rcnn_voc.html)

```
> python3 object-detection/src/train_rcnn.py 
/home/sam/miniconda3/envs/mxnet/lib/python3.6/site-packages/mxnet/gluon/parameter.py:678: UserWarning: Constant parameter "fasterrcnn0_rpn0_rpnanchorgenerator0_anchor_" does not support grad_req other than "null", and new value "write" is ignored.
  'is ignored.'.format(self.name, req))
INFO:root:Namespace(amp=False, batch_size=8, dataset='voc', disable_hybridization=False, epochs=20, executor_threads=1, gpus='0', horovod=False, kv_store='nccl', log_interval=100, lr=0.001, lr_decay=0.1, lr_decay_epoch='14,20', lr_warmup=-1, lr_warmup_factor=0.3333333333333333, mixup=False, momentum=0.9, network='resnet50_v1b', no_mixup_epochs=20, norm_layer=None, num_workers=4, resume='', save_interval=1, save_prefix='faster_rcnn_resnet50_v1b_voc', seed=233, start_epoch=0, static_alloc=False, use_fpn=False, val_interval=1, verbose=False, wd=0.0005)
INFO:root:Start training from [Epoch 0]
Traceback (most recent call last):
  File "object-detection/src/train_rcnn.py", line 501, in <module>
    train(net, train_data, val_data, eval_metric, batch_size, ctx, args)
  File "object-detection/src/train_rcnn.py", line 410, in train
    executor.put(data)
  File "/home/sam/miniconda3/envs/mxnet/lib/python3.6/site-packages/gluoncv/utils/parallel.py", line 119, in put
    out = self._parallizable.forward_backward(x)
  File "object-detection/src/train_rcnn.py", line 271, in forward_backward
    box_targets, box_masks, _ = net(data, gt_box, gt_label)
  File "/home/sam/miniconda3/envs/mxnet/lib/python3.6/site-packages/mxnet/gluon/block.py", line 548, in __call__
    out = self.forward(*args)
  File "/home/sam/miniconda3/envs/mxnet/lib/python3.6/site-packages/mxnet/gluon/block.py", line 915, in forward
    return self._call_cached_op(x, *args)
  File "/home/sam/miniconda3/envs/mxnet/lib/python3.6/site-packages/mxnet/gluon/block.py", line 805, in _call_cached_op
    self._build_cache(*args)
  File "/home/sam/miniconda3/envs/mxnet/lib/python3.6/site-packages/mxnet/gluon/block.py", line 757, in _build_cache
    data, out = self._get_graph(*args)
  File "/home/sam/miniconda3/envs/mxnet/lib/python3.6/site-packages/mxnet/gluon/block.py", line 749, in _get_graph
    out = self.hybrid_forward(symbol, *grouped_inputs, **params)  # pylint: disable=no-value-for-parameter
TypeError: hybrid_forward() takes from 3 to 4 positional arguments but 5 were given
```

**Version:**
```
>>> import mxnet
>>> mxnet.__version__
'1.5.1'
```

**Comment by Jerryzcn** [comment]
this is weird. could you try `python train_faster_rcnn.py --batch-size 1 --gpus 0`

**Comment by Jerryzcn** [comment]
actually, did u install gluoncv using pip or from source?

**Comment by Jerryzcn** [comment]
it is probably because the latest gluoncv works with gluoncv0.6 only not 0.5
