### ISSUE TITLE
Failed to find any forward convolution algorithm.

### ISSUE THREAD

**Issue by likangGit** [dmlc/gluon-cv#101]
mxnet version:mxnet_cu80-1.2.0.0b20180509
gluoncv version: 0.1.0
when i ran train_ssd.py with default parameters, this problem occurs.  
```
Traceback (most recent call last):
  File "/media/ryan/F/Projects/PycharmProjects/mxnetSSD/train_ssd.py", line 257, in <module>
    train(net, train_data, val_data, classes, args)
  File "/media/ryan/F/Projects/PycharmProjects/mxnetSSD/train_ssd.py", line 184, in train
    anchors, cls_preds, gt_boxes, gt_ids)
  File "/media/ryan/F/virtualenv/mxnet/lib/python3.5/site-packages/mxnet/gluon/block.py", line 413, in __call__
    return self.forward(*args)
  File "/media/ryan/F/virtualenv/mxnet/lib/python3.5/site-packages/gluoncv/model_zoo/ssd/target.py", line 40, in forward
    samples = self._sampler(matches, cls_preds, ious)
  File "/media/ryan/F/virtualenv/mxnet/lib/python3.5/site-packages/mxnet/gluon/block.py", line 413, in __call__
    return self.forward(*args)
  File "/media/ryan/F/virtualenv/mxnet/lib/python3.5/site-packages/gluoncv/model_zoo/samplers.py", line 78, in forward
    y[np.where(x.asnumpy() >= 0)] = 1  # assign positive samples
  File "/media/ryan/F/virtualenv/mxnet/lib/python3.5/site-packages/mxnet/ndarray/ndarray.py", line 1890, in asnumpy
    ctypes.c_size_t(data.size)))
  File "/media/ryan/F/virtualenv/mxnet/lib/python3.5/site-packages/mxnet/base.py", line 149, in check_call
    raise MXNetError(py_str(_LIB.MXGetLastError()))
mxnet.base.MXNetError: [18:06:16] src/operator/nn/./cudnn/cudnn_convolution-inl.h:744: Failed to find any forward convolution algorithm.
```

**Comment by likangGit** [comment]
@zhreshold yes!you are right. I change batch size to 10. Now, it can run normally. thanks for your advice.

**Comment by PistonY** [comment]
显存不足
