### ISSUE TITLE
resnet50_v1d unused parameters causing DeferredInitializationError

### ISSUE THREAD

**Issue by skaldesh** [dmlc/gluon-cv#1055]
Hi, I am using the script to train a classification model with my own dataset that is offered in the gluon-cv tutorial, found here: https://gluon-cv.mxnet.io/build/examples_classification/transfer_learning_minc.html

The only change I made is in line 196, where I replaced `ResNet50_v2` with `resnet50_v1d`.

When running the script, it then fails with this exception:

```python
/usr/local/lib/python3.5/dist-packages/mxnet/gluon/block.py:548: UserWarning: Parameter resnetv1d_dense1_bias, resnetv1d_dense1_weight is not used by any computation. Is this intended?
  out = self.forward(*args)
[13:52:07] src/operator/nn/./cudnn/./cudnn_algoreg-inl.h:97: Running performance tests to find the best convolution algorithm, this can take a while... (set the environment variable MXNET_CUDNN_AUTOTUNE_DEFAULT to 0 to disable)
Traceback (most recent call last):
  File "transfer_learning_minc.py", line 271, in <module>
    trainer.step(batch_size)
  File "/usr/local/lib/python3.5/dist-packages/mxnet/gluon/trainer.py", line 327, in step
    self._init_kvstore()
  File "/usr/local/lib/python3.5/dist-packages/mxnet/gluon/trainer.py", line 222, in _init_kvstore
    arg_arrays = {param.name: param.data(self._contexts[0]) for param in self._params}
  File "/usr/local/lib/python3.5/dist-packages/mxnet/gluon/trainer.py", line 222, in <dictcomp>
    arg_arrays = {param.name: param.data(self._contexts[0]) for param in self._params}
  File "/usr/local/lib/python3.5/dist-packages/mxnet/gluon/parameter.py", line 543, in data
    return self._check_and_get(self._data, ctx)
  File "/usr/local/lib/python3.5/dist-packages/mxnet/gluon/parameter.py", line 234, in _check_and_get
    "num_features, etc., for network layers."%(self.name))
mxnet.gluon.parameter.DeferredInitializationError: Parameter 'resnetv1d_dense1_weight' has not been initialized yet because initialization was deferred. Actual initialization happens during the first forward pass. Please pass one batch of data through the network before accessing Parameters. You can also avoid deferred initialization by specifying in_units, num_features, etc., for network layers.
```

Since I am relatively unexperienced so far, I do not know what I need to do in order to fix this...

**Comment by zhreshold** [comment]
Due to legacy code divergence, Resnet50_v2 and resnet50_v1d has different name for the output fullyconnected layer.
Please replace `finetune_net.output` with `finetune_net.fc`.
Sorry about the confusion.

**Comment by skaldesh** [comment]
Thank you!
