### ISSUE TITLE
ValueError: "siamrpn_alexnet_v2_otb15" is not among the following model list:

### ISSUE THREAD

**Issue by josephceli** [dmlc/gluon-cv#1193]
I'm trying to run the SiamRPN model based off the following web page

https://gluon-cv.mxnet.io/build/examples_tracking/demo_SiamRPN.html

I get the following error

python demo.py
Traceback (most recent call last):
  File "demo.py", line 106, in <module>
    net = model_zoo.get_model(opt.netwrok, ctx=mx.cpu(), pretrained=True)
  File "/Users/josephceli/.pyenv/versions/3.6.1/lib/python3.6/site-packages/gluoncv/model_zoo/model_zoo.py", line 342, in get_model
    raise ValueError(err_str)
ValueError: "siamrpn_alexnet_v2_otb15" is not among the following model list:

**Comment by josephceli** [comment]
fixed by installing the nightly build
