### ISSUE TITLE
Finetuning Faster RCNN : TypeError: 'RPNAnchorGenerator' object is not iterable

### ISSUE THREAD

**Issue by samuel-chp** [dmlc/gluon-cv#1196]
Hi,

I am trying to finetune a Faster RCNN model to detect tables in invoice images. 

I have converted my data as .rec files following [this tutorial](https://gluon-cv.mxnet.io/build/examples_datasets/detection_custom.html#lst-record-dataset).  

I first load the model through 
```net = gcv.model_zoo.get_model('faster_rcnn_resnet101_v1d_custom', classes=classes, pretrained_base=False)```

Next I try to create a dataloader and this is where I encountered the following error : 
```
Traceback (most recent call last):
  File "C:\Users\Me\Documents\Mes environnements python\Projet3\lib\site-packages\IPython\core\interactiveshell.py", line 3331, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-2-47768daa3293>", line 77, in <module>
    batch_size, len(ctx))
  File "<ipython-input-2-47768daa3293>", line 28, in get_dataloader
    train_transform(net.short, net.max_size, net, ashape=net.ashape, multi_stage=True)),
  File "C:\Users\Me\Documents\Mes environnements python\Projet3\lib\site-packages\gluoncv\data\transforms\presets\rcnn.py", line 165, in __init__
    for ag in anchor_generator:
TypeError: 'RPNAnchorGenerator' object is not iterable
```

Here is my get_dataloader function that I copied from the file train_faster_rcnn.py : 
```
def get_dataloader(net, train_dataset, val_dataset, train_transform, val_transform, batch_size,
                   num_shards):
    """Get dataloader."""
    train_bfn = FasterRCNNTrainBatchify(net, num_shards)
    if hasattr(train_dataset, 'get_im_aspect_ratio'):
        im_aspect_ratio = train_dataset.get_im_aspect_ratio()
    else:
        im_aspect_ratio = [1.] * len(train_dataset)
    train_sampler = \
        gcv.nn.sampler.SplitSortedBucketSampler(im_aspect_ratio, batch_size,
                                                num_parts=1,
                                                part_index=0,
                                                shuffle=True)
    train_loader = mx.gluon.data.DataLoader(train_dataset.transform(
        train_transform(net.short, net.max_size, net, ashape=net.ashape, multi_stage=True)),
        batch_sampler=train_sampler, batchify_fn=train_bfn, num_workers=0)
    val_bfn = Tuple(*[Append() for _ in range(3)])
    short = net.short[-1] if isinstance(net.short, (tuple, list)) else net.short
    # validation use 1 sample per device
    val_loader = mx.gluon.data.DataLoader(
        val_dataset.transform(val_transform(short, net.max_size)), num_shards, False,
        batchify_fn=val_bfn, last_batch='keep', num_workers=0)
    return train_loader, val_loader
```

The rest of my .py file looks like the one in the pikachu tutorial for fine tune object detectors.

I tried with multiple faster_rcnn models but same results. Do you have any idea how to make this works ?

Thanks

**Comment by Jerryzcn** [comment]
Try change multi_stage=True to False. Did you copied the RCNN dataloader from tutorial.

**Comment by breeky** [comment]
Thanks it worked with multi_stage=False, but what does "multi stage features" mean ?

```
multi_stage : boolean, default is False
        Whether the network output multi stage features.
```

I copied the RCNN dataloader from the file "train_faster_rcnn.py" which I downloaded from this [link](https://gluon-cv.mxnet.io/build/examples_detection/finetune_detection.html#sphx-glr-build-examples-detection-finetune-detection-py).

**Comment by breeky** [comment]
Now I get the following error :
```
Traceback (most recent call last):
  File "C:\Users\Me\Documents\Mes environnements python\Projet3\lib\site-packages\mxnet\ndarray\ndarray.py", line 2501, in array
    source_array = np.array(source_array, dtype=dtype)
ValueError: setting an array element with a sequence.
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "C:\Users\Me\Documents\Mes environnements python\Projet3\lib\site-packages\IPython\core\interactiveshell.py", line 3331, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-2-28d96c64c43c>", line 106, in <module>
    box_targets = gluon.utils.split_and_load(batch[2], ctx_list=ctx, batch_axis=0)
  File "C:\Users\Me\Documents\Mes environnements python\Projet3\lib\site-packages\mxnet\gluon\utils.py", line 115, in split_and_load
    data = ndarray.array(data, ctx=ctx_list[0])
  File "C:\Users\Me\Documents\Mes environnements python\Projet3\lib\site-packages\mxnet\ndarray\utils.py", line 146, in array
    return _array(source_array, ctx=ctx, dtype=dtype)
  File "C:\Users\Me\Documents\Mes environnements python\Projet3\lib\site-packages\mxnet\ndarray\ndarray.py", line 2503, in array
    raise TypeError('source_array must be array like object')
TypeError: source_array must be array like object
```

I am using this model : `net = gcv.model_zoo.get_model('faster_rcnn_resnet50_v1b_coco', pretrained=True)` and the error occurs here :

```
for param in net.collect_params().values():
    if param._data is None:
        param.initialize()

# Training GPU / CPU
try:
    a = mx.nd.zeros((1,), ctx=mx.gpu(0))
    ctx = [mx.gpu(0)]
    print("Using GPU") # I am using the GPU
except:
    ctx = [mx.cpu()]
    print("Using CPU")

train_data, val_data = get_dataloader(
    net, train_dataset, val_dataset,
    FasterRCNNDefaultTrainTransform, FasterRCNNDefaultValTransform,
    batch_size, len(ctx))

# Training
net.collect_params().reset_ctx(ctx)
trainer = gluon.Trainer(
    net.collect_params(), 'sgd',
    {'learning_rate': 0.001, 'wd': 0.0005, 'momentum': 0.9})

mbox_loss = gcv.loss.SSDMultiBoxLoss()
ce_metric = mx.metric.Loss('CrossEntropy')
smoothl1_metric = mx.metric.Loss('SmoothL1')

for epoch in range(0, 2):
    ce_metric.reset()
    smoothl1_metric.reset()
    tic = time.time()
    btic = time.time()
    net.hybridize(static_alloc=True, static_shape=True)
    for i, batch in enumerate(train_data):
        batch_size = batch[0].shape[0]
        data = gluon.utils.split_and_load(batch[0], ctx_list=ctx, batch_axis=0)
        cls_targets = gluon.utils.split_and_load(batch[1], ctx_list=ctx, batch_axis=0)
        box_targets = gluon.utils.split_and_load(batch[2], ctx_list=ctx, batch_axis=0)
```

**Comment by Jerryzcn** [comment]
so multi_stage is when u use FPN. meaning features are extracted from multiple feature maps

**Comment by Jerryzcn** [comment]
i think the split batch is for SSD, you can try the one in FasterRCNN training script. The input data format is different for SSD and FasterRCNN
