### ISSUE TITLE
ssd_512_resnet18_v1_voc is not available

### ISSUE THREAD

**Issue by zxy844288792** [dmlc/gluon-cv#1244]
Python 3.7.4
mxnet                              1.5.1.post0
gluoncv                            0.6.0

Hello,

I got model is not available while I tried to get the models defined here:
https://github.com/dmlc/gluon-cv/blob/bdfb0e9efbcd37a2a98d8fda45393fbe6b69be24/gluoncv/model_zoo/model_zoo.py#L107

Error messgae is shown below:
>> net = gluoncv.model_zoo.get_model('ssd_512_resnet18_v1_voc', pretrained=True)
/opt/anaconda3/lib/python3.7/site-packages/mxnet/gluon/block.py:1159: UserWarning: Cannot decide type for the following arguments. Consider providing them as input:
	data: None
  input_sym_arg_type = in_param.infer_type()[0]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/anaconda3/lib/python3.7/site-packages/gluoncv/model_zoo/model_zoo.py", line 343, in get_model
    net = _models[name](**kwargs)
  File "/opt/anaconda3/lib/python3.7/site-packages/gluoncv/model_zoo/ssd/presets.py", line 245, in ssd_512_resnet18_v1_voc
    pretrained_base=pretrained_base, **kwargs)
  File "/opt/anaconda3/lib/python3.7/site-packages/gluoncv/model_zoo/ssd/ssd.py", line 397, in get_ssd
    net.load_parameters(get_model_file(full_name, tag=pretrained, root=root), ctx=ctx)
  File "/opt/anaconda3/lib/python3.7/site-packages/gluoncv/model_zoo/model_store.py", line 224, in get_model_file
    short_hash=short_hash(name))
  File "/opt/anaconda3/lib/python3.7/site-packages/gluoncv/model_zoo/model_store.py", line 193, in short_hash
    raise ValueError('Pretrained model for {name} is not available.'.format(name=name))
ValueError: Pretrained model for ssd_512_resnet18_v1_voc is not available.

**Comment by zhreshold** [comment]
There's no pretrained ssd resnet18, you can try resnet50 instead
