### ISSUE TITLE
Unable to Download faster_rcnn_fpn_syncbn_resnest269_coco model

### ISSUE THREAD

**Issue by MayurDeshmukh10** [dmlc/gluon-cv#1297]
While loading model using following code -
`net = gcv.model_zoo.get_model('faster_rcnn_fpn_syncbn_resnest269_coco', pretrained=True)`

I'm getting an error like this - 

Traceback (most recent call last):
  File "detect.py", line 11, in <module>
    net = gcv.model_zoo.get_model('faster_rcnn_fpn_syncbn_resnest269_coco', pretrained=True)
  File "/home/mayur/.local/lib/python3.6/site-packages/gluoncv/model_zoo/model_zoo.py", line 384, in get_model
    net = _models[name](**kwargs)
  File "/home/mayur/.local/lib/python3.6/site-packages/gluoncv/model_zoo/rcnn/faster_rcnn/predefined_models.py", line 767, in faster_rcnn_fpn_syncbn_resnest269_coco
    pos_iou_thresh=0.5, pos_ratio=0.25, max_num_gt=100, **kwargs)
  File "/home/mayur/.local/lib/python3.6/site-packages/gluoncv/model_zoo/rcnn/faster_rcnn/faster_rcnn.py", line 505, in get_faster_rcnn
    net.load_parameters(get_model_file(full_name, tag=pretrained, root=root), ctx=ctx,
  File "/home/mayur/.local/lib/python3.6/site-packages/gluoncv/model_zoo/model_store.py", line 242, in get_model_file
    short_hash=short_hash(name))
  File "/home/mayur/.local/lib/python3.6/site-packages/gluoncv/model_zoo/model_store.py", line 211, in short_hash
    raise ValueError('Pretrained model for {name} is not available.'.format(name=name))
ValueError: Pretrained model for faster_rcnn_fpn_syncbn_resnest269_coco is not available.

But I was able to download the model using the link -  https://apache-mxnet.s3-accelerate.dualstack.amazonaws.com/gluon/models/faster_rcnn_fpn_syncbn_resnest269_coco-b7d778f5.zip  and then manually pasting it in the models folder

**Comment by zhreshold** [comment]
You probably want to update gluoncv which has updated model zoo definitions recently.
