### ISSUE TITLE
pickle module issue

### ISSUE THREAD

**Issue by alighofrani95** [dmlc/gluon-cv#1401]
I have tried to fine-tune i3dnl on my custom dataset
in my local system, my implementation based on gluoncv doc works fine but when I switch the code to the GPU server with the same package version installed I faced the error below.

python  3.7.4, cudatoolkit  10.0.130, mxnet-cu100mkl  1.6.0b20191125, gluoncv  0.8.0b20200727

I've tried both single and multi GPU and decrease workers and  prefetch ratio but the problem still reminds

Load 1442 training samples and 338 validation samples.
Traceback (most recent call last):
  File "i3dnl2000.py", line 566, in <module>
    main()
  File "i3dnl2000.py", line 339, in main
    train_data, val_data, batch_fn = get_data_loader(opt, batch_size, num_workers, logger)
  File "i3dnl2000.py", line 265, in get_data_loader
    prefetch=int(opt.prefetch_ratio * num_workers), last_batch='rollover')
  File "Anaconda3\lib\site-packages\mxnet\gluon\data\dataloader.py", line 641, in __init__
    initargs=[self._dataset, is_np_shape(), is_np_array()])
  File "Anaconda3\lib\multiprocessing\context.py", line 119, in Pool
    context=self.get_context())
  File "Anaconda3\lib\multiprocessing\pool.py", line 176, in __init__
    self._repopulate_pool()
  File "Anaconda3\lib\multiprocessing\pool.py", line 241, in _repopulate_pool
    w.start()
  File "Anaconda3\lib\multiprocessing\process.py", line 112, in start
    self._popen = self._Popen(self)
  File "Anaconda3\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "Anaconda3\lib\multiprocessing\popen_spawn_win32.py", line 89, in __init__
    reduction.dump(process_obj, to_child)
  File "Anaconda3\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
TypeError: can't pickle module objects

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "Anaconda3\lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "Anaconda3\lib\multiprocessing\spawn.py", line 115, in _main
    self = reduction.pickle.load(from_parent)
EOFError: Ran out of input

**Comment by zhreshold** [comment]
Are you using windows gpu server? 
Windows use spawn which requires individual functions to be pickable.
You can try wrapping the code in `train.py` to named functions.

**Comment by imyangshao** [comment]
> Are you using windows gpu server?
> Windows use spawn which requires individual functions to be pickable.
> You can try wrapping the code in `train.py` to named functions.

What is the reason for this? @zhreshold

**Comment by zhreshold** [comment]
It's the limitation of python implementation
