### ISSUE TITLE
Running train_ssd.py

### ISSUE THREAD

**Issue by ahchang2** [dmlc/gluon-cv#1413]
I'm trying to run train_ssd.py file and encountered the following problem which I've never met before.
Here's the error:
Traceback (most recent call last):
  File "train_ssd_new.py", line 12, in <module>
    import gluoncv as gcv
  File "/usr/local/lib/python3.6/dist-packages/gluoncv/__init__.py", line 12, in <module>
    from . import data
  File "/usr/local/lib/python3.6/dist-packages/gluoncv/data/__init__.py", line 31, in <module>
    from .kitti.kitti_dataset import KITTIRAWDataset, KITTIOdomDataset
  File "/usr/local/lib/python3.6/dist-packages/gluoncv/data/kitti/__init__.py", line 2, in <module>
    from .kitti_dataset import *
  File "/usr/local/lib/python3.6/dist-packages/gluoncv/data/kitti/kitti_dataset.py", line 21, in <module>
    from .kitti_utils import generate_depth_map
  File "/usr/local/lib/python3.6/dist-packages/gluoncv/data/kitti/kitti_utils.py", line 12, in <module>
    from mxnet.util import is_np_array
ImportError: cannot import name 'is_np_array'

The file train_ssd_new.py is just the same as train_ssd.py on gluoncv tutorial (I just renamed it)
Does anyone know the reason for this?

**Comment by zhreshold** [comment]
You are using gluoncv against old mxnet build. Try upgrade mxnet `pip install -U mxnet-cu100` for example to solve this issue

**Comment by ahchang2** [comment]
Hi, thanks for your response. I changed my installation to 'pip install -U mxnet-cu100 gluoncv' but I still got the same error. I'm thinking whether the source code for ssd training needs to be updated or something else is still wrong.
