### ISSUE TITLE
"IndexError: too many indices for array" when training SSD with subset of VOC

### ISSUE THREAD

**Issue by kangks** [dmlc/gluon-cv#1416]
I would like to train a SSD model with only subset of VOC -  [ "person", "dog" ].

However, I encountered error with [VOCLike](https://gluon-cv.mxnet.io/build/examples_datasets/detection_custom.html?highlight=voclike#pascal-voc-like) with subset of classes. It works if I expand to full classes:

```
class VOCLike(gdata.VOCDetection):
    CLASSES = ['person','dog'] # not working
    # CLASSES = ['aeroplane', 'bicycle', 'bird', 'boat', 'bottle', 'bus', 'car', 'cat', 'chair', 'cow', 'diningtable', 'dog', 'horse', 'motorbike', 'person', 'pottedplant', 'sheep', 'sofa', 'train', 'tvmonitor'] # this works

    def __init__(self, root, splits, transform=None, index_map=None, preload_label=True):
        super(VOCLike, self).__init__(root, splits, transform, index_map, preload_label)
```

Error message:

```
INFO:root:Namespace(amp=False, batch_size=32, dali=False, data_shape=300, dataset='voc', dataset_root='.', epochs=240, gpus='0', horovod=False, log_interval=100, lr=0.001, lr_decay=0.1, lr_decay_epoch='160,200', momentum=0.9, network='resnet34_v1b', num_workers=4, resume='', save_interval=10, save_prefix='ssd_300_resnet34_v1b_voc', seed=233, start_epoch=0, syncbn=False, val_interval=1, wd=0.0005)
INFO:root:Start training from [Epoch 0]
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/Users/richardkang/training/lib/python3.8/site-packages/mxnet/gluon/data/dataloader.py", line 450, in _worker_fn
    batch = batchify_fn([_worker_dataset[i] for i in samples])
  File "/Users/richardkang/training/lib/python3.8/site-packages/mxnet/gluon/data/dataloader.py", line 450, in <listcomp>
    batch = batchify_fn([_worker_dataset[i] for i in samples])
  File "/Users/richardkang/training/lib/python3.8/site-packages/mxnet/gluon/data/dataset.py", line 219, in __getitem__
    return self._fn(*item)
  File "/Users/richardkang/training/lib/python3.8/site-packages/gluoncv/data/transforms/presets/ssd.py", line 153, in __call__
    bbox = tbbox.translate(label, x_offset=expand[0], y_offset=expand[1])
  File "/Users/richardkang/training/lib/python3.8/site-packages/gluoncv/data/transforms/bbox.py", line 160, in translate
    bbox[:, :2] += (x_offset, y_offset)
IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "train_ssd.py", line 431, in <module>
    train(net, train_data, val_data, eval_metric, ctx, args)
  File "train_ssd.py", line 316, in train
    for i, batch in enumerate(train_data):
  File "/Users/richardkang/training/lib/python3.8/site-packages/mxnet/gluon/data/dataloader.py", line 506, in __next__
    batch = pickle.loads(ret.get(self._timeout))
  File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/pool.py", line 771, in get
    raise self._value
IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed
```

To reproduce
1. Prepare [VOC dataset](https://gluon-cv.mxnet.io/build/examples_datasets/pascal_voc.html#sphx-glr-build-examples-datasets-pascal-voc-py) 
2. Download [train_ssd.py](https://gluon-cv.mxnet.io/build/examples_detection/train_ssd_voc.html#sphx-glr-build-examples-detection-train-ssd-voc-py)
3. Create `VOCLike` and replace `gdata.VOCDetection` in `train_ssd.py::get_dataset()` to use `VOCLike`
4. Define only sub classes in `VOCLike`
5. Run the `train_ssd.py` and the error will appear

System details:
1. OS: OSX 10.15.5
2. Python: Python 3.8.5, pip details:
```
% python -m pip freeze
certifi==2020.6.20
chardet==3.0.4
cycler==0.10.0
gluoncv==0.8.0
graphviz==0.8.4
idna==2.10
imgviz==1.2.2
kiwisolver==1.2.0
labelme==4.5.6
lxml==4.5.2
matplotlib==3.3.0
mxnet==1.6.0
numpy==1.19.1
opencv-python==4.4.0.40
Pillow==7.2.0
portalocker==2.0.0
pyparsing==2.4.7
PyQt5==5.15.0
PyQt5-sip==12.8.0
python-dateutil==2.8.1
PyYAML==5.3.1
QtPy==1.9.0
requests==2.24.0
scipy==1.5.2
six==1.15.0
termcolor==1.1.0
tqdm==4.48.2
urllib3==1.25.10
```

**Comment by Aktcob** [comment]
hi, u can check the bbox shape before this line <bbox[:, :2] += (x_offset, y_offset)>.

u may find out that the bbox shape is None, since there is no person or dog in some pictures. So u should make sure that every img in the subset of VOC dataset.
