### ISSUE TITLE
Cannot import name 'is_np_array' when importing GluonCV with mxnet-mkl

### ISSUE THREAD

**Issue by LewsTherin511** [dmlc/gluon-cv#1423]
Hi,
I've been trying to install gluoncv with mkl on Windows 10, using Python 3.6 and Anaconda3.

I created a conda environment, and ran:

`pip install --upgrade mxnet-mkl gluoncv`

Everything goes ok, the process installs mxnet-mkl (1.5.0) and gluoncv (0.8.0). However, when I try to import gluoncv I get this error:

`
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\sense\anaconda3\envs\gluon_mkl\lib\site-packages\gluoncv\__init__.py", line 12, in <module>
    from . import data
  File "C:\Users\sense\anaconda3\envs\gluon_mkl\lib\site-packages\gluoncv\data\__init__.py", line 31, in <module>
    from .kitti.kitti_dataset import KITTIRAWDataset, KITTIOdomDataset
  File "C:\Users\sense\anaconda3\envs\gluon_mkl\lib\site-packages\gluoncv\data\kitti\__init__.py", line 2, in <module>
    from .kitti_dataset import *
  File "C:\Users\sense\anaconda3\envs\gluon_mkl\lib\site-packages\gluoncv\data\kitti\kitti_dataset.py", line 21, in <module>
    from .kitti_utils import generate_depth_map
  File "C:\Users\sense\anaconda3\envs\gluon_mkl\lib\site-packages\gluoncv\data\kitti\kitti_utils.py", line 12, in <module>
    from mxnet.util import is_np_array
ImportError: cannot import name 'is_np_array'
`

I overcame the issue by commenting the line:

`
from .kitti.kitti_dataset import KITTIRAWDataset, KITTIOdomDataset
`

in C:\Users\sense\anaconda3\envs\gluon_mkl\Lib\site-packages\gluoncv\data\__init.py__

**Comment by bryanyzhu** [comment]
`is_np_array ` is a new feature in mxnet 1.6 and later versions. If you install mxnet 1.5, there will be this import error. 

Right now, I think commenting out this line would be the best approach to avoid this import error. We will push fix for this very soon.
