### ISSUE TITLE
Error in prepaing ucf101 dataset

### ISSUE THREAD

**Issue by fasttigare** [dmlc/gluon-cv#1468]
I tried to follow prepare ucf101 dataset tutorial and downloaded ucf101.py which download a file ucf101.zip of 6.5 GB but after finish downloading I am getting this error

multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "C:\Python38\lib\multiprocessing\pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "C:\Python38\lib\multiprocessing\pool.py", line 48, in mapstar
    return list(map(*args))
  File "C:\Python38\ucf101.py", line 22, in dump_frames
    out_full_path = osp.join(args.out_dir, vid_name)
NameError: name 'args' is not defined
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Python38\ucf101.py", line 337, in <module>
    decode_video(args)
  File "C:\Python38\ucf101.py", line 177, in decode_video
    pool.map(dump_frames, zip(
  File "C:\Python38\lib\multiprocessing\pool.py", line 364, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "C:\Python38\lib\multiprocessing\pool.py", line 768, in get
    raise self._value
NameError: name 'args' is not defined

please advice

**Comment by bryanyzhu** [comment]
This error maybe environment specific. The reason is args is not a global param. For now, a simple fix would be providing the path manually in the code, instead of using args.
