### ISSUE TITLE
Can't install. Win10

### ISSUE THREAD

**Issue by StevenJokess** [dmlc/gluon-cv#1577]
C:\Users\a8679>activate mxnet

(mxnet) C:\Users\a8679>pip install gluoncv --upgrade
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Collecting gluoncv
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/5a/d7/e6429bd8d6ee2ff8123f7afc197a5a60901bbf9afc47e1f30c484cf22540/gluoncv-0.9.0-py2.py3-none-any.whl (997 kB)
     |████████████████████████████████| 997 kB 6.4 MB/s
Requirement already satisfied: pandas in c:\users\a8679\anaconda3\envs\mxnet\lib\site-packages (from gluoncv) (1.1.0)
Requirement already satisfied: numpy in c:\users\a8679\anaconda3\envs\mxnet\lib\site-packages (from gluoncv) (1.16.6)
Requirement already satisfied: requests in c:\users\a8679\anaconda3\envs\mxnet\lib\site-packages (from gluoncv) (2.18.4)Requirement already satisfied: matplotlib in c:\users\a8679\anaconda3\envs\mxnet\lib\site-packages (from gluoncv) (3.3.0)
Requirement already satisfied: Pillow in c:\users\a8679\anaconda3\envs\mxnet\lib\site-packages (from gluoncv) (7.2.0)
Collecting autocfg
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/94/4d/71221541472d0e45351cf9b11b0c3d55c032b80dcf8bc0763b28791e3dd3/autocfg-0.0.6-py2.py3-none-any.whl (13 kB)
Collecting autogluon.core
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/5b/01/4d115e1f2b9a98b22d181ab75443479ecc4e09b77700876808edab415d37/autogluon.core-0.0.16b20201224-py3-none-any.whl (243 kB)
     |████████████████████████████████| 243 kB 6.8 MB/s
Requirement already satisfied: tornado>=5.0.1 in c:\users\a8679\anaconda3\envs\mxnet\lib\site-packages (from autogluon.core->gluoncv) (6.0.4)
Requirement already satisfied: graphviz<0.9.0,>=0.8.1 in c:\users\a8679\anaconda3\envs\mxnet\lib\site-packages (from autogluon.core->gluoncv) (0.8.4)
Collecting dill==0.3.3
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/52/d6/79f40d230895fa1ce3b6af0d22e0ac79c65175dc069c194b79cc8e05a033/dill-0.3.3-py2.py3-none-any.whl (81 kB)
     |████████████████████████████████| 81 kB 5.1 MB/s
Collecting autograd>=1.3
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/23/12/b58522dc2cbbd7ab939c7b8e5542c441c9a06a8eccb00b3ecac04a739896/autograd-1.3.tar.gz (38 kB)
Collecting ConfigSpace<=0.4.16
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/3a/f9/685e3cb6e2a87e4989b83950dfbe8cecc49fd158f4ff3d1368dc62014e8d/ConfigSpace-0.4.16.tar.gz (964 kB)
     |████████████████████████████████| 964 kB ...
  Installing build dependencies ... error
  ERROR: Command errored out with exit status 2:
   command: 'c:\users\a8679\anaconda3\envs\mxnet\python.exe' 'c:\users\a8679\anaconda3\envs\mxnet\lib\site-packages\pip' install --ignore-installed --no-user --prefix 'C:\Users\a8679\AppData\Local\Temp\pip-build-env-4nrsevdw\overlay' --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.tuna.tsinghua.edu.cn/simple -- setuptools wheel numpy Cython
       cwd: None
  Complete output (79 lines):
  Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
  Collecting Cython
    Downloading https://pypi.tuna.tsinghua.edu.cn/packages/79/f4/28002920834b292a4dece255d59860c9996d16002f1bca30d7794e0b7884/Cython-0.29.21-cp37-cp37m-win_amd64.whl (1.6 MB)
  Collecting numpy
    Downloading https://pypi.tuna.tsinghua.edu.cn/packages/5f/a5/24db9dd5c4a8b6c8e495289f17c28e55601769798b0e2e5a5aeb2abd247b/numpy-1.19.4-cp37-cp37m-win_amd64.whl (12.9 MB)
  ERROR: Exception:
  Traceback (most recent call last):
    File "c:\users\a8679\anaconda3\envs\mxnet\lib\site-packages\pip\_vendor\urllib3\response.py", line 438, in _error_catcher
      yield
    File "c:\users\a8679\anaconda3\envs\mxnet\lib\site-packages\pip\_vendor\urllib3\response.py", line 519, in read
      data = self._fp.read(amt) if not fp_closed else b""
    File "c:\users\a8679\anaconda3\envs\mxnet\lib\site-packages\pip\_vendor\cachecontrol\filewrapper.py", line 62, in read
      data = self.__fp.read(amt)
    File "c:\users\a8679\anaconda3\envs\mxnet\lib\http\client.py", line 457, in read
      n = self.readinto(b)
    File "c:\users\a8679\anaconda3\envs\mxnet\lib\http\client.py", line 501, in readinto
      n = self.fp.readinto(b)
    File "c:\users\a8679\anaconda3\envs\mxnet\lib\socket.py", line 589, in readinto
      return self._sock.recv_into(b)
    File "c:\users\a8679\anaconda3\envs\mxnet\lib\ssl.py", line 1071, in recv_into
      return self.read(nbytes, buffer)
    File "c:\users\a8679\anaconda3\envs\mxnet\lib\ssl.py", line 929, in read
      return self._sslobj.read(len, buffer)
  socket.timeout: The read operation timed out

  During handling of the above exception, another exception occurred:

  Traceback (most recent call last):
    File "c:\users\a8679\anaconda3\envs\mxnet\lib\site-packages\pip\_internal\cli\base_command.py", line 224, in _main
      status = self.run(options, args)
    File "c:\users\a8679\anaconda3\envs\mxnet\lib\site-packages\pip\_internal\cli\req_command.py", line 180, in wrapper
      return func(self, options, args)
    File "c:\users\a8679\anaconda3\envs\mxnet\lib\site-packages\pip\_internal\commands\install.py", line 321, in run
      reqs, check_supported_wheels=not options.target_dir
    File "c:\users\a8679\anaconda3\envs\mxnet\lib\site-packages\pip\_internal\resolution\resolvelib\resolver.py", line 122, in resolve
      requirements, max_rounds=try_to_avoid_resolution_too_deep,
    File "c:\users\a8679\anaconda3\envs\mxnet\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 445, in resolve
      state = resolution.resolve(requirements, max_rounds=max_rounds)
    File "c:\users\a8679\anaconda3\envs\mxnet\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 339, in resolve
      failure_causes = self._attempt_to_pin_criterion(name, criterion)
    File "c:\users\a8679\anaconda3\envs\mxnet\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 207, in _attempt_to_pin_criterion
      criteria = self._get_criteria_to_update(candidate)
    File "c:\users\a8679\anaconda3\envs\mxnet\lib\site-packages\pip\_vendor\resolvelib\resolvers.py", line 198, in _get_criteria_to_update
      for r in self._p.get_dependencies(candidate):
    File "c:\users\a8679\anaconda3\envs\mxnet\lib\site-packages\pip\_internal\resolution\resolvelib\provider.py", line 172, in get_dependencies
      for r in candidate.iter_dependencies(with_requires)
    File "c:\users\a8679\anaconda3\envs\mxnet\lib\site-packages\pip\_internal\resolution\resolvelib\provider.py", line 171, in <listcomp>
      r
    File "c:\users\a8679\anaconda3\envs\mxnet\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 257, in iter_dependencies
      requires = self.dist.requires() if with_requires else ()
    File "c:\users\a8679\anaconda3\envs\mxnet\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 239, in dist
      self._prepare()
    File "c:\users\a8679\anaconda3\envs\mxnet\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 226, in _prepare
      dist = self._prepare_distribution()
    File "c:\users\a8679\anaconda3\envs\mxnet\lib\site-packages\pip\_internal\resolution\resolvelib\candidates.py", line 319, in _prepare_distribution
      self._ireq, parallel_builds=True,
    File "c:\users\a8679\anaconda3\envs\mxnet\lib\site-packages\pip\_internal\operations\prepare.py", line 480, in prepare_linked_requirement
      return self._prepare_linked_requirement(req, parallel_builds)
    File "c:\users\a8679\anaconda3\envs\mxnet\lib\site-packages\pip\_internal\operations\prepare.py", line 505, in _prepare_linked_requirement
      self.download_dir, hashes,
    File "c:\users\a8679\anaconda3\envs\mxnet\lib\site-packages\pip\_internal\operations\prepare.py", line 257, in unpack_url
      hashes=hashes,
    File "c:\users\a8679\anaconda3\envs\mxnet\lib\site-packages\pip\_internal\operations\prepare.py", line 130, in get_http_url
      from_path, content_type = download(link, temp_dir.path)
    File "c:\users\a8679\anaconda3\envs\mxnet\lib\site-packages\pip\_internal\network\download.py", line 163, in __call__
      for chunk in chunks:
    File "c:\users\a8679\anaconda3\envs\mxnet\lib\site-packages\pip\_internal\cli\progress_bars.py", line 168, in iter
      for x in it:
    File "c:\users\a8679\anaconda3\envs\mxnet\lib\site-packages\pip\_internal\network\utils.py", line 88, in response_chunks
      decode_content=False,
    File "c:\users\a8679\anaconda3\envs\mxnet\lib\site-packages\pip\_vendor\urllib3\response.py", line 576, in stream
      data = self.read(amt=amt, decode_content=decode_content)
    File "c:\users\a8679\anaconda3\envs\mxnet\lib\site-packages\pip\_vendor\urllib3\response.py", line 541, in read
      raise IncompleteRead(self._fp_bytes_read, self.length_remaining)
    File "c:\users\a8679\anaconda3\envs\mxnet\lib\contextlib.py", line 130, in __exit__
      self.gen.throw(type, value, traceback)
    File "c:\users\a8679\anaconda3\envs\mxnet\lib\site-packages\pip\_vendor\urllib3\response.py", line 443, in _error_catcher
      raise ReadTimeoutError(self._pool, None, "Read timed out.")
  pip._vendor.urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='pypi.tuna.tsinghua.edu.cn', port=443): Read timed out.
  ----------------------------------------
ERROR: Command errored out with exit status 2: 'c:\users\a8679\anaconda3\envs\mxnet\python.exe' 'c:\users\a8679\anaconda3\envs\mxnet\lib\site-packages\pip' install --ignore-installed --no-user --prefix 'C:\Users\a8679\AppData\Local\Temp\pip-build-env-4nrsevdw\overlay' --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.tuna.tsinghua.edu.cn/simple -- setuptools wheel numpy Cython Check the logs for full command output.

**Comment by StevenJokess** [comment]
(mxnet) C:\Users\a8679>pip install gluoncv --upgrade --user
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Collecting gluoncv
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/5a/d7/e6429bd8d6ee2ff8123f7afc197a5a60901bbf9afc47e1f30c484cf22540/gluoncv-0.9.0-py2.py3-none-any.whl (997 kB)
Requirement already satisfied: matplotlib in c:\users\a8679\anaconda3\envs\mxnet\lib\site-packages (from gluoncv) (3.3.0)
Requirement already satisfied: Pillow in c:\users\a8679\anaconda3\envs\mxnet\lib\site-packages (from gluoncv) (7.2.0)
Requirement already satisfied: numpy in c:\users\a8679\anaconda3\envs\mxnet\lib\site-packages (from gluoncv) (1.16.6)
Requirement already satisfied: pandas in c:\users\a8679\anaconda3\envs\mxnet\lib\site-packages (from gluoncv) (1.1.0)
Requirement already satisfied: requests in c:\users\a8679\anaconda3\envs\mxnet\lib\site-packages (from gluoncv) (2.18.4)
Collecting autocfg
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/94/4d/71221541472d0e45351cf9b11b0c3d55c032b80dcf8bc0763b28791e3dd3/autocfg-0.0.6-py2.py3-none-any.whl (13 kB)
Collecting autogluon.core
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/5b/01/4d115e1f2b9a98b22d181ab75443479ecc4e09b77700876808edab415d37/autogluon.core-0.0.16b20201224-py3-none-any.whl (243 kB)
Requirement already satisfied: tornado>=5.0.1 in c:\users\a8679\anaconda3\envs\mxnet\lib\site-packages (from autogluon.core->gluoncv) (6.0.4)
Requirement already satisfied: graphviz<0.9.0,>=0.8.1 in c:\users\a8679\anaconda3\envs\mxnet\lib\site-packages (from autogluon.core->gluoncv) (0.8.4)
Collecting dill==0.3.3
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/52/d6/79f40d230895fa1ce3b6af0d22e0ac79c65175dc069c194b79cc8e05a033/dill-0.3.3-py2.py3-none-any.whl (81 kB)
Collecting autograd>=1.3
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/23/12/b58522dc2cbbd7ab939c7b8e5542c441c9a06a8eccb00b3ecac04a739896/autograd-1.3.tar.gz (38 kB)
Collecting ConfigSpace<=0.4.16
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/3a/f9/685e3cb6e2a87e4989b83950dfbe8cecc49fd158f4ff3d1368dc62014e8d/ConfigSpace-0.4.16.tar.gz (964 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... - ** On entry to DGEBAL parameter number  3 had an illegal value
 ** On entry to DGEHRD  parameter number  2 had an illegal value
 ** On entry to DORGHR DORGQR parameter number  2 had an illegal value
 ** On entry to DHSEQR parameter number  4 had an illegal value
error
    ERROR: Command errored out with exit status 1:
     command: 'c:\users\a8679\anaconda3\envs\mxnet\python.exe' 'c:\users\a8679\anaconda3\envs\mxnet\lib\site-packages\pip\_vendor\pep517\_in_process.py' prepare_metadata_for_build_wheel 'C:\Users\a8679\AppData\Local\Temp\tmpslcak60g'
         cwd: C:\Users\a8679\AppData\Local\Temp\pip-install-dky2n9n9\configspace_d95147191a5b4aa0aac84b2c10b677ba
    Complete output (55 lines):
    running dist_info
    creating C:\Users\a8679\AppData\Local\Temp\pip-modern-metadata-fveclgvt\ConfigSpace.egg-info
    writing C:\Users\a8679\AppData\Local\Temp\pip-modern-metadata-fveclgvt\ConfigSpace.egg-info\PKG-INFO
    writing dependency_links to C:\Users\a8679\AppData\Local\Temp\pip-modern-metadata-fveclgvt\ConfigSpace.egg-info\dependency_links.txt
    writing requirements to C:\Users\a8679\AppData\Local\Temp\pip-modern-metadata-fveclgvt\ConfigSpace.egg-info\requires.txt
    writing top-level names to C:\Users\a8679\AppData\Local\Temp\pip-modern-metadata-fveclgvt\ConfigSpace.egg-info\top_level.txt
    writing manifest file 'C:\Users\a8679\AppData\Local\Temp\pip-modern-metadata-fveclgvt\ConfigSpace.egg-info\SOURCES.txt'
    Traceback (most recent call last):
      File "c:\users\a8679\anaconda3\envs\mxnet\lib\site-packages\pip\_vendor\pep517\_in_process.py", line 280, in <module>
        main()
      File "c:\users\a8679\anaconda3\envs\mxnet\lib\site-packages\pip\_vendor\pep517\_in_process.py", line 263, in main
        json_out['return_val'] = hook(**hook_input['kwargs'])
      File "c:\users\a8679\anaconda3\envs\mxnet\lib\site-packages\pip\_vendor\pep517\_in_process.py", line 133, in prepare_metadata_for_build_wheel
        return hook(metadata_directory, config_settings)
      File "C:\Users\a8679\AppData\Local\Temp\pip-build-env-4vuu5ih3\overlay\Lib\site-packages\setuptools\build_meta.py", line 161, in prepare_metadata_for_build_wheel
        self.run_setup()
      File "C:\Users\a8679\AppData\Local\Temp\pip-build-env-4vuu5ih3\overlay\Lib\site-packages\setuptools\build_meta.py", line 254, in run_setup
        self).run_setup(setup_script=setup_script)
      File "C:\Users\a8679\AppData\Local\Temp\pip-build-env-4vuu5ih3\overlay\Lib\site-packages\setuptools\build_meta.py", line 145, in run_setup
        exec(compile(code, __file__, 'exec'), locals())
      File "setup.py", line 110, in <module>
        classifiers=CLASSIFIERS,
      File "C:\Users\a8679\AppData\Local\Temp\pip-build-env-4vuu5ih3\overlay\Lib\site-packages\setuptools\__init__.py", line 153, in setup
        return distutils.core.setup(**attrs)
      File "c:\users\a8679\anaconda3\envs\mxnet\lib\distutils\core.py", line 148, in setup
        dist.run_commands()
      File "c:\users\a8679\anaconda3\envs\mxnet\lib\distutils\dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "c:\users\a8679\anaconda3\envs\mxnet\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "C:\Users\a8679\AppData\Local\Temp\pip-build-env-4vuu5ih3\overlay\Lib\site-packages\setuptools\command\dist_info.py", line 31, in run
        egg_info.run()
      File "C:\Users\a8679\AppData\Local\Temp\pip-build-env-4vuu5ih3\overlay\Lib\site-packages\setuptools\command\egg_info.py", line 298, in run
        self.find_sources()
      File "C:\Users\a8679\AppData\Local\Temp\pip-build-env-4vuu5ih3\overlay\Lib\site-packages\setuptools\command\egg_info.py", line 305, in find_sources
        mm.run()
      File "C:\Users\a8679\AppData\Local\Temp\pip-build-env-4vuu5ih3\overlay\Lib\site-packages\setuptools\command\egg_info.py", line 536, in run
        self.add_defaults()
      File "C:\Users\a8679\AppData\Local\Temp\pip-build-env-4vuu5ih3\overlay\Lib\site-packages\setuptools\command\egg_info.py", line 572, in add_defaults
        sdist.add_defaults(self)
      File "c:\users\a8679\anaconda3\envs\mxnet\lib\distutils\command\sdist.py", line 228, in add_defaults
        self._add_defaults_ext()
      File "c:\users\a8679\anaconda3\envs\mxnet\lib\distutils\command\sdist.py", line 311, in _add_defaults_ext
        build_ext = self.get_finalized_command('build_ext')
      File "c:\users\a8679\anaconda3\envs\mxnet\lib\distutils\cmd.py", line 299, in get_finalized_command
        cmd_obj.ensure_finalized()
      File "c:\users\a8679\anaconda3\envs\mxnet\lib\distutils\cmd.py", line 107, in ensure_finalized
        self.finalize_options()
      File "setup.py", line 28, in finalize_options
        import numpy
      File "C:\Users\a8679\AppData\Local\Temp\pip-build-env-4vuu5ih3\overlay\Lib\site-packages\numpy\__init__.py", line 305, in <module>
        _win_os_check()
      File "C:\Users\a8679\AppData\Local\Temp\pip-build-env-4vuu5ih3\overlay\Lib\site-packages\numpy\__init__.py", line 302, in _win_os_check
        raise RuntimeError(msg.format(__file__)) from None
    RuntimeError: The current Numpy installation ('C:\\Users\\a8679\\AppData\\Local\\Temp\\pip-build-env-4vuu5ih3\\overlay\\Lib\\site-packages\\numpy\\__init__.py') fails to pass a sanity check due to a bug in the windows runtime. See this issue for more information: https://tinyurl.com/y3dm3h86
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'c:\users\a8679\anaconda3\envs\mxnet\python.exe' 'c:\users\a8679\anaconda3\envs\mxnet\lib\site-packages\pip\_vendor\pep517\_in_process.py' prepare_metadata_for_build_wheel 'C:\Users\a8679\AppData\Local\Temp\tmpslcak60g' Check the logs for full command output.

**Comment by DB11051998** [comment]
@StevenJokess i also faced the same error. did you find anyway to solve this?

**Comment by dai-ichiro** [comment]
It works fine on my environment.

```
pip install mxnet
pip install configspace==0.4.14
pip uninstall numpy
pip install numpy==1.19.3
pip install gluoncv
```

I hope this helps.

**Comment by DB11051998** [comment]
Hii!
which python did u use.ok let me try on pip environment.

**Comment by DB11051998** [comment]
Thank you!
It worked!
