### ISSUE TITLE
train_faster_rcnn.py crashes when training with 2 GPUs, data loader error?

### ISSUE THREAD

**Issue by gilbertfrancois** [dmlc/gluon-cv#1587]
I tried running the `train_faster_rcnn.py` script, but run into errors. I have prepared the Pascal VOC dataset with the script provided by gluon-cv.
   
System:
python 3.7
cuda 10.2
mxnet-cu102 1.7.0
gluon-cv 0.9.0

The `train_faster_rcnn.py` script is from the 0.9.0 tagged release.

The used command:
```
python train_faster_rcnn.py --gpus 0,1 --dataset voc --network resnet50_v1b
```

The output:
```
[17:25:51] src/storage/storage.cc:110: Using GPUPooledRoundedStorageManager.
[17:25:52] src/storage/storage.cc:110: Using GPUPooledRoundedStorageManager.
/home/ubuntu/.cache/pypoetry/virtualenvs/object_detection-SOISfXoO-py3.7/lib/python3.7/site-packages/mxnet/gluon/parameter.py:709: UserWarning: Constant parameter "fasterrcnn0_rpn0_rpnanchorgenerator0_anc
hor_" does not support grad_req other than "null", and new value "write" is ignored.
  'is ignored.'.format(self.name, req))
INFO:root:Namespace(amp=False, batch_size=1, custom_model=None, dataset='voc', disable_hybridization=False, epochs=20, executor_threads=1, gpus='0,1', horovod=False, kv_store='device', log_interval=1
00, lr=0.001, lr_decay=0.1, lr_decay_epoch='14,20', lr_warmup=-1, lr_warmup_factor=0.3333333333333333, mixup=False, momentum=0.9, network='resnet50_v1b', no_mixup_epochs=20, norm_layer=None, num_work
ers=4, rcnn_smoothl1_rho=1.0, resume='', rpn_smoothl1_rho=0.1111111111111111, save_interval=1, save_prefix='faster_rcnn_resnet50_v1b_voc', seed=233, start_epoch=0, static_alloc=False, use_fpn=False,
val_interval=1, verbose=False, wd=0.0005)
INFO:root:Start training from [Epoch 0]
WARNING:root:Batch size cannot be evenly split. Trying to shard 1 items into 2 shards
WARNING:root:Batch size cannot be evenly split. Trying to shard 1 items into 2 shards
WARNING:root:Batch size cannot be evenly split. Trying to shard 1 items into 2 shards
WARNING:root:Batch size cannot be evenly split. Trying to shard 1 items into 2 shards
multiprocessing.pool.RemoteTraceback:
"""                                                                                                                                                                                           [84/1438]
Traceback (most recent call last):
  File "/home/ubuntu/.pyenv/versions/3.7.7/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/home/ubuntu/.cache/pypoetry/virtualenvs/object_detection-SOISfXoO-py3.7/lib/python3.7/site-packages/mxnet/gluon/data/dataloader.py", line 429, in _worker_fn
    batch = batchify_fn([_worker_dataset[i] for i in samples])
  File "/home/ubuntu/.cache/pypoetry/virtualenvs/object_detection-SOISfXoO-py3.7/lib/python3.7/site-packages/gluoncv/data/batchify.py", line 416, in __call__
    sharded_img = self._img_pad(data[0])
  File "/home/ubuntu/.cache/pypoetry/virtualenvs/object_detection-SOISfXoO-py3.7/lib/python3.7/site-packages/gluoncv/data/batchify.py", line 249, in __call__
    self._num_shards, True)
  File "/home/ubuntu/.cache/pypoetry/virtualenvs/object_detection-SOISfXoO-py3.7/lib/python3.7/site-packages/gluoncv/data/batchify.py", line 42, in _pad_arrs_to_max_length
    max_lengths = [np.max(l, axis=0, keepdims=len(pad_axis) == 1) for l in original_length]
  File "/home/ubuntu/.cache/pypoetry/virtualenvs/object_detection-SOISfXoO-py3.7/lib/python3.7/site-packages/gluoncv/data/batchify.py", line 42, in <listcomp>
    max_lengths = [np.max(l, axis=0, keepdims=len(pad_axis) == 1) for l in original_length]
  File "<__array_function__ internals>", line 6, in amax
  File "/home/ubuntu/.cache/pypoetry/virtualenvs/object_detection-SOISfXoO-py3.7/lib/python3.7/site-packages/numpy/core/fromnumeric.py", line 2706, in amax
    keepdims=keepdims, initial=initial, where=where)
  File "/home/ubuntu/.cache/pypoetry/virtualenvs/object_detection-SOISfXoO-py3.7/lib/python3.7/site-packages/numpy/core/fromnumeric.py", line 87, in _wrapreduction
    return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
ValueError: zero-size array to reduction operation maximum which has no identity
"""
The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "train_faster_rcnn.py", line 667, in <module>
    train(net, train_data, val_data, eval_metric, batch_size, ctx, args)
  File "train_faster_rcnn.py", line 509, in train
    for i, batch in enumerate(train_data):
  File "/home/ubuntu/.cache/pypoetry/virtualenvs/object_detection-SOISfXoO-py3.7/lib/python3.7/site-packages/mxnet/gluon/data/dataloader.py", line 484, in __next__
    batch = pickle.loads(ret.get(self._timeout))
  File "/home/ubuntu/.pyenv/versions/3.7.7/lib/python3.7/multiprocessing/pool.py", line 657, in get
    raise self._value
ValueError: zero-size array to reduction operation maximum which has no identity
Exception ignored in: <module 'threading' from '/home/ubuntu/.pyenv/versions/3.7.7/lib/python3.7/threading.py'>
Traceback (most recent call last):
  File "/home/ubuntu/.pyenv/versions/3.7.7/lib/python3.7/threading.py", line 1307, in _shutdown
    lock.acquire()
KeyboardInterrupt
```

I tried `--kv-store nccl` and `--kv-store device`: no difference.

Note that the `train_faster_rcnn.py` script works with 1 GPU (`--gpus 0`). Is there an option I need to activate to make it work with 2 GPUs? Any help is appreciated. :)

**Comment by gilbertfrancois** [comment]
I forgot to set the batch-size to 2, equal to the number of gpus. Training works now.
