### ISSUE TITLE
voc_detection.py has an error about AttributeError: 'NDArray' object has no attribute 'flat'

### ISSUE THREAD

**Issue by yunfanLu** [dmlc/gluon-cv#159]
`python /data/yunfan.lu/App/App/github.yunfan/gluon-cv/train_ssd.py`

```
INFO:root:[Epoch 0] Training cost: 3146.936, CrossEntropy=5.021, SmoothL1=2.144
Traceback (most recent call last):
  File "/data/yunfan.lu/App/App/github.yunfan/gluon-cv/train_ssd.py", line 248, in <module>
    train(net, train_data, val_data, eval_metric, args)
  File "/data/yunfan.lu/App/App/github.yunfan/gluon-cv/train_ssd.py", line 213, in train
    map_name, mean_ap = validate(net, val_data, ctx, eval_metric)
  File "/data/yunfan.lu/App/App/github.yunfan/gluon-cv/train_ssd.py", line 138, in validate
    eval_metric.update(det_bboxes, det_ids, det_scores, gt_bboxes, gt_ids, gt_difficults)
  File "/data/yunfan.lu/App/github.data/gluon-cv/gluoncv/utils/metrics/voc_detection.py", line 99, in update
    valid_pred = np.where(pred_label.flat >= 0)[0]
AttributeError: 'NDArray' object has no attribute 'flat'
```

**Comment by zhreshold** [comment]
Fix will be merged soon. master is not blocked but it will be quick.
