### ISSUE TITLE
model_store: FileExistsError: [Errno 17] File exists: '/root/.mxnet/models'

### ISSUE THREAD

**Issue by ChaiBapchya** [dmlc/gluon-cv#1590]
Upon running the maskrcnn example, I hit the above error.
Following stack trace:
```
[1,22]<stdout>:Downloading /root/.mxnet/models/resnet50_v1b-0ecdba34.zip from https://apache-mxnet.s3-accelerate.dualstack.amazonaws.com/gluon/models/resnet50_v1b-0ecdba34.zip...
[1,37]<stdout>:Downloading /root/.mxnet/models/resnet50_v1b-0ecdba34.zip from https://apache-mxnet.s3-accelerate.dualstack.amazonaws.com/gluon/models/resnet50_v1b-0ecdba34.zip...
[1,38]<stdout>:Traceback (most recent call last):
[1,38]<stdout>:  File "train_mask_rcnn.py", line 698, in <module>
[1,38]<stdout>:    per_device_batch_size=args.batch_size // num_gpus, **kwargs)
[1,38]<stdout>:  File "/usr/local/lib/python3.7/site-packages/gluoncv/model_zoo/model_zoo.py", line 403, in get_model
[1,38]<stdout>:    net = _models[name](**kwargs)
[1,38]<stdout>:  File "/usr/local/lib/python3.7/site-packages/gluoncv/model_zoo/rcnn/mask_rcnn/predefined_models.py", line 97, in mask_rcnn_fpn_resnet50_v1b_coco
[1,38]<stdout>:    base_network = resnet50_v1b(pretrained=pretrained_base, dilated=False, use_global_stats=True)
[1,38]<stdout>:  File "/usr/local/lib/python3.7/site-packages/gluoncv/model_zoo/resnetv1b.py", line 367, in resnet50_v1b
[1,38]<stdout>:    tag=pretrained, root=root), ctx=ctx)
[1,38]<stdout>:  File "/usr/local/lib/python3.7/site-packages/gluoncv/model_zoo/model_store.py", line 274, in get_model_file
[1,38]<stdout>:    os.makedirs(root)
[1,38]<stdout>:  File "/usr/local/lib/python3.7/os.py", line 223, in makedirs
[1,38]<stdout>:    mkdir(name, mode)
[1,38]<stdout>:FileExistsError: [Errno 17] File exists: '/root/.mxnet/models'
--------------------------------------------------------------------------
MPI_ABORT was invoked on rank 38 in communicator MPI COMMUNICATOR 5 DUP FROM 0
with errorcode 1.
NOTE: invoking MPI_ABORT causes Open MPI to kill all MPI processes.
You may or may not see output from other processes, depending on
exactly when Open MPI kills them.
--------------------------------------------------------------------------
```

Looks like multiple ranks are trying to create the folder simultaneously.

Note: This error is hit intermittently [not reproducible 100% times]

**Comment by karan6181** [comment]
Looks like a bug. Wondering if this 2 lines (https://github.com/dmlc/gluon-cv/blob/master/gluoncv/model_zoo/model_store.py#L281-L282) should go inside https://github.com/dmlc/gluon-cv/blob/master/gluoncv/model_zoo/model_store.py#L284. Is this the case or there is something else? @zhreshold

**Comment by zhreshold** [comment]
I think adding `exist_ok=True` to mkdirs should solve the issue

**Comment by ChaiBapchya** [comment]
Thanks for pointing it out. Can you take a look at that small PR? @zhreshold
