### ISSUE TITLE
onnx model 

### ISSUE THREAD

**Issue by alicera** [dmlc/gluon-cv#1601]
OS: ubuntu18.04
NGC : nvcr.io/nvidia/mxnet:20.12-py3
ONNX: 1.7.0 1.8.0

I run the project to deal with onnx
https://chai-bapat.medium.com/5min-gluon-model-to-onnx-e8ed0eea754e

Error:
[04:56:43] ../src/storage/storage.cc:199: Using Pooled (Naive) StorageManager for CPU
resnest50 downloaded
resnest50 hybridized
resnest50 exported
Traceback (most recent call last):
File "pre.py", line 27, in
onnx_mxnet.export_model(sym, params, [input_shape], np.float32, onnx_file)
File "/opt/mxnet/python/mxnet/contrib/onnx/mx2onnx/export_model.py", line 81, in export_model
onnx_graph = converter.create_onnx_graph_proto(sym_obj, params_obj, input_shape,
File "/opt/mxnet/python/mxnet/contrib/onnx/mx2onnx/export_onnx.py", line 245, in create_onnx_graph_proto
converted = MXNetGraph.convert_layer(
File "/opt/mxnet/python/mxnet/contrib/onnx/mx2onnx/export_onnx.py", line 86, in convert_layer
raise AttributeError("No conversion function registered for op type %s yet." % op)
AttributeError: No conversion function registered for op type _contrib_AdaptiveAvgPooling2D yet.

**Comment by Aktcob** [comment]
No conversion function registered for op type _contrib_AdaptiveAvgPooling2D yet.

**Comment by alicera** [comment]
Thanks.
Yes, I know.

**Comment by yinweisu** [comment]
Many operators are not supported by the current version of mxnet. Therefore, in order to export to onnx, you'll have to either build from source mxnet yourself or use this tool to add those operators to your mxnet. You are free to restore those updates with this script was well.
