### ISSUE TITLE
Pytorch feature extraction failed to extract the features

### ISSUE THREAD

**Issue by mrkstt** [dmlc/gluon-cv#1642]
Hi all,

I tried the PyTorch feature extraction by running the following command:
`python feat_extract_pytorch.py --config-file configuration/i3d_resnet50_v1_feat.yaml`

but the process never stops, even when the process took only one short video. The output is as follows:

```
Saving extracted features to ./logs/i3d_resnet50_v1_kinetics400/2021-03-27-08-24-37/features
Building model for feature extraction
Pre-trained model is successfully loaded from the model zoo.
Extracting features from 1 videos.
/home/tekom/anaconda3/envs/i3d_extractor/lib/python3.7/site-packages/gluoncv/torch/data/video_cls/dataset_classification.py:136: UserWarning: video Explosion008_x264.mp4 not correctly loaded during validation
  warnings.warn("video {} not correctly loaded during validation".format(sample))
^CTraceback (most recent call last):
  File "feat_extract_pytorch.py", line 70, in <module>
    main(cfg, save_path)
  File "feat_extract_pytorch.py", line 42, in main
    for vid, vtuple in enumerate(val_dataset):
  File "/home/tekom/anaconda3/envs/i3d_extractor/lib/python3.7/site-packages/gluoncv/torch/data/video_cls/dataset_classification.py", line 136, in __getitem__
    warnings.warn("video {} not correctly loaded during validation".format(sample))
```

I followed this tutorial but haven't yet properly obtained the results.
[https://cv.gluon.ai/build/examples_torch_action_recognition/extract_feat.html](https://cv.gluon.ai/build/examples_torch_action_recognition/extract_feat.html)

any help would be appreciated.

**Comment by mrkstt** [comment]
I incorrectly set the path, it works properly now.
