### ISSUE TITLE
Error when export center_net_resnet50_v1b_coco model to onnx

### ISSUE THREAD

**Issue by zhouwei5113** [dmlc/gluon-cv#1645]
Traceback (most recent call last):
  File "export2onnx.py", line 62, in <module>
    model.export_onnx()
  File "export2onnx.py", line 57, in export_onnx
    return onnx_mxnet.export_model(sym, params, [self.input_shape], np.float32, self.onnx_model)
  File "C:\Users\Administrator\AppData\Roaming\Python\Python37\site-packages\mxnet\contrib\onnx\mx2onnx\export_model.py", line 83, in export_model
    verbose=verbose)
  File "C:\Users\Administrator\AppData\Roaming\Python\Python37\site-packages\mxnet\contrib\onnx\mx2onnx\export_onnx.py", line 253, in create_onnx_graph_proto
    idx=idx
  File "C:\Users\Administrator\AppData\Roaming\Python\Python37\site-packages\mxnet\contrib\onnx\mx2onnx\export_onnx.py", line 90, in convert_layer
    raise AttributeError("No conversion function registered for op type %s yet." % op) 
AttributeError: No conversion function registered for op type topk yet.

**Comment by zhouwei5113** [comment]
How to fix this error？

**Comment by yinweisu** [comment]
Hi @zhouwei5113,
Sorry, I should mention in the readme that many operators are not supported by the current version of mxnet. Therefore, in order to export to onnx, you'll have to either build from source mxnet yourself or use this tool to add those operators to your mxnet. You are free to restore those updates with this script was well.
