### ISSUE TITLE
ImportError: Unable to import modules due to missing `mxnet` & `torch`.

### ISSUE THREAD

**Issue by talhaanwarch** [dmlc/gluon-cv#1661]
When i try `import mxnet`, its imported without any error. But when I try `from gluoncv.auto.estimators import ImageClassificationEstimator` i got following error
```
ImportError: Unable to import modules due to missing `mxnet` & `torch`.
```
I am using windows 10 with cuda 10.1 installed. 
Here are the packaged installed
autocfg==0.0.8
autogluon.core==0.2.0
autograd==1.3
bcrypt==3.2.0
boto3==1.17.73
botocore==1.20.73
certifi==2020.12.5
cffi==1.14.5
chardet==3.0.4
click==8.0.0
cloudpickle==1.6.0
colorama==0.4.4
ConfigSpace==0.4.18
cryptography==3.4.7
cycler==0.10.0
Cython==0.29.23
dask==2021.5.0
decord==0.5.2
dill==0.3.3
distributed==2021.5.0
fsspec==2021.5.0
future==0.18.2
gluoncv==0.10.1.post0
graphviz==0.8.4
HeapDict==1.0.1
idna==2.6
jmespath==0.10.0
joblib==1.0.1
kiwisolver==1.3.1
locket==0.2.1
matplotlib==3.4.2
msgpack==1.0.2
mxnet-cu101==1.5.0
numpy==1.16.6
opencv-python==4.5.2.52
pandas==1.2.4
paramiko==2.7.2
partd==1.2.0
Pillow==8.2.0
portalocker==2.3.0
protobuf==3.17.0
psutil==5.8.0
pycparser==2.20
PyNaCl==1.4.0
pyparsing==2.4.7
python-dateutil==2.8.1
pytz==2021.1
pywin32==300
PyYAML==5.4.1
requests==2.18.4
s3transfer==0.4.2
scikit-learn==0.24.2
scipy==1.6.3
six==1.16.0
sortedcontainers==2.4.0
tblib==1.7.0
tensorboardX==2.2
threadpoolctl==2.1.0
toolz==0.11.1
tornado==6.1
tqdm==4.60.0
urllib3==1.22
yacs==0.1.8
zict==2.0.0

**Comment by zhreshold** [comment]
@talhaanwarch   can you import gluoncv directly? what's the output of `import gluoncv` ?

**Comment by talhaanwarch** [comment]
@zhreshold  same error with `import gluoncv`

**Comment by asymptotic** [comment]
I'm having this same issue. Python 3.7, having the issue with 0.11.0. Anyone out there have any ideas?

```
Python 3.7.5 (default, Feb 23 2021, 13:22:40) 
[GCC 8.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import mxnet as mx
>>> import gluoncv
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/greengrass/v2/work/variant.DLR/greengrass_ml/greengrass_ml_dlr_venv/lib/python3.7/site-packages/gluoncv/__init__.py", line 33, in <module>
    raise ImportError('Unable to import modules due to missing `mxnet` & `torch`. '
ImportError: Unable to import modules due to missing `mxnet` & `torch`. You should install at least one deep learning framework.
>>> mx.__version__
'1.8.0'
```
