### ISSUE TITLE
 Check failed: dim_size_is_known(d[i]): Shape dim size must be known, while received -1

### ISSUE THREAD

**Issue by wolfworld6** [dmlc/gluon-cv#1736]
when i run the script feat_extract.py,i got this error,why?
fast_input shape:  (1, 3, 18, 224, 224)
slow_input shape:  (1, 3, 0, 224, 224)
Fast x shape:  (1, 8, 18, 112, 112)
[13:23:12] ../src/operator/nn/./cudnn/./cudnn_algoreg-inl.h:97: Running performance tests to find the best convolution algorithm, this can take a while... (set the environment variable MXNET_CUDNN_AUTOTUNE_DEFAULT to 0 to disable)
Traceback (most recent call last):
  File "feat_extract.py", line 215, in <module>
    main(logger)
  File "feat_extract.py", line 199, in main
    video_feat = net(video_input.astype(opt.dtype, copy=False))
  File "/opt/conda/envs/torch6/lib/python3.7/site-packages/mxnet/gluon/block.py", line 682, in __call__
    out = self.forward(*args)
  File "/opt/conda/envs/torch6/lib/python3.7/site-packages/mxnet/gluon/block.py", line 1309, in forward
    return self.hybrid_forward(ndarray, x, *args, **params)
  File "/opt/conda/envs/torch6/lib/python3.7/site-packages/gluoncv/model_zoo/action_recognition/slowfast.py", line 364, in hybrid_forward
    slow = self.SlowPath(F, slow_input, lateral)
  File "/opt/conda/envs/torch6/lib/python3.7/site-packages/gluoncv/model_zoo/action_recognition/slowfast.py", line 380, in SlowPath
    x = self.slow_conv1(x)                          # bx64x4x112x112, input is bx3x4x224x224
  File "/opt/conda/envs/torch6/lib/python3.7/site-packages/mxnet/gluon/block.py", line 682, in __call__
    out = self.forward(*args)
  File "/opt/conda/envs/torch6/lib/python3.7/site-packages/mxnet/gluon/block.py", line 1309, in forward
    return self.hybrid_forward(ndarray, x, *args, **params)
  File "/opt/conda/envs/torch6/lib/python3.7/site-packages/mxnet/gluon/nn/conv_layers.py", line 145, in hybrid_forward
    act = getattr(F, self._op_name)(x, weight, name='fwd', **self._kwargs)
  File "<string>", line 169, in Convolution
  File "/opt/conda/envs/torch6/lib/python3.7/site-packages/mxnet/_ctypes/ndarray.py", line 91, in _imperative_invoke
    ctypes.byref(out_stypes)))
  File "/opt/conda/envs/torch6/lib/python3.7/site-packages/mxnet/base.py", line 246, in check_call
    raise get_last_ffi_error()
mxnet.base.MXNetError: Traceback (most recent call last):
  File "../include/mxnet/./tuple.h", line 544
MXNetError: Check failed: dim_size_is_known(d[i]): Shape dim size must be known, while received -1

**Comment by naynikaw** [comment]
Hi, I'm facing the same issue, were you able to find a work around?
