### ISSUE TITLE
Bad file descriptor ERROR when run train_faster_rcnn.py

### ISSUE THREAD

**Issue by yunfanLu** [dmlc/gluon-cv#177]
Hi, when I try to run train_faster_rcnn.py and eval_faster_rcnn.py  it is fail by some OSError,Bad file descriptor. Thanks for your attenation.

```
INFO:root:Namespace(batch_size=2, dataset='voc', epochs=30, gpus='0,1', log_interval=100, lr=0.001, lr_decay=0.1, lr_decay_epoch='14,20', momentum=0.9, network='resnet50_v2a', num_workers=8, resume='', save_interval=1, save_prefix='faster_rcnn_resnet50_v2a_voc', seed=233, start_epoch=0, val_interval=1, verbose=False, wd=0.0005)
INFO:root:Start training from [Epoch 0]
Process Process-2:
Traceback (most recent call last):
  File "/home/users/yunfan.lu/anaconda2/envs/py3/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/home/users/yunfan.lu/anaconda2/envs/py3/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/users/yunfan.lu/anaconda2/envs/py3/lib/python3.6/site-packages/mxnet-1.2.0-py3.6.egg/mxnet/gluon/data/dataloader.py", line 157, in worker_loop
    data_queue.put((idx, batch))
  File "/home/users/yunfan.lu/anaconda2/envs/py3/lib/python3.6/multiprocessing/queues.py", line 341, in put
    obj = _ForkingPickler.dumps(obj)
  File "/home/users/yunfan.lu/anaconda2/envs/py3/lib/python3.6/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
  File "/home/users/yunfan.lu/anaconda2/envs/py3/lib/python3.6/site-packages/mxnet-1.2.0-py3.6.egg/mxnet/gluon/data/dataloader.py", line 64, in reduce_ndarray
    fd = multiprocessing.reduction.DupFd(fd)
  File "/home/users/yunfan.lu/anaconda2/envs/py3/lib/python3.6/multiprocessing/reduction.py", line 191, in DupFd
    return resource_sharer.DupFd(fd)
  File "/home/users/yunfan.lu/anaconda2/envs/py3/lib/python3.6/multiprocessing/resource_sharer.py", line 48, in __init__
    new_fd = os.dup(fd)
OSError: [Errno 9] Bad file descriptor
Process Process-6:
Traceback (most recent call last):
  File "/home/users/yunfan.lu/anaconda2/envs/py3/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/home/users/yunfan.lu/anaconda2/envs/py3/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/users/yunfan.lu/anaconda2/envs/py3/lib/python3.6/site-packages/mxnet-1.2.0-py3.6.egg/mxnet/gluon/data/dataloader.py", line 157, in worker_loop
    data_queue.put((idx, batch))
  File "/home/users/yunfan.lu/anaconda2/envs/py3/lib/python3.6/multiprocessing/queues.py", line 341, in put
    obj = _ForkingPickler.dumps(obj)
  File "/home/users/yunfan.lu/anaconda2/envs/py3/lib/python3.6/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
  File "/home/users/yunfan.lu/anaconda2/envs/py3/lib/python3.6/site-packages/mxnet-1.2.0-py3.6.egg/mxnet/gluon/data/dataloader.py", line 64, in reduce_ndarray
    fd = multiprocessing.reduction.DupFd(fd)
  File "/home/users/yunfan.lu/anaconda2/envs/py3/lib/python3.6/multiprocessing/reduction.py", line 191, in DupFd
    return resource_sharer.DupFd(fd)
  File "/home/users/yunfan.lu/anaconda2/envs/py3/lib/python3.6/multiprocessing/resource_sharer.py", line 48, in __init__
    new_fd = os.dup(fd)
OSError: [Errno 9] Bad file descriptor
Process Process-7:
Traceback (most recent call last):
  File "/home/users/yunfan.lu/anaconda2/envs/py3/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/home/users/yunfan.lu/anaconda2/envs/py3/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/users/yunfan.lu/anaconda2/envs/py3/lib/python3.6/site-packages/mxnet-1.2.0-py3.6.egg/mxnet/gluon/data/dataloader.py", line 157, in worker_loop
    data_queue.put((idx, batch))
  File "/home/users/yunfan.lu/anaconda2/envs/py3/lib/python3.6/multiprocessing/queues.py", line 341, in put
    obj = _ForkingPickler.dumps(obj)
  File "/home/users/yunfan.lu/anaconda2/envs/py3/lib/python3.6/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)

```

**Comment by zhreshold** [comment]
try reduce the `num_worker`, linux systems have small limit of opened files. 

See `ulimit -n`, I think it's 1024 in most linux distributions.

**Comment by zhreshold** [comment]
And make sure you update mxnet to the latest version.

**Comment by masahi** [comment]
in my case, train_ssd.py works fine with num_worker = 6, but train_faster_rcnn.py gives the Bad file descriptor error whenever num_worker > 0. num_worker = 0 works fine.

**Comment by zhreshold** [comment]
This error is fixed in https://github.com/apache/incubator-mxnet/pull/11159. So any MXNet version later than this merged PR should be fine.
