### ISSUE TITLE
error in run SSD

### ISSUE THREAD

**Issue by zhaoxin111** [dmlc/gluon-cv#212]
When I run train_ssd.py. sth wrong in dataloader,I don't know how to fix it? Any help will be awesome! 

python train_ssd.py --gpus 2 --network resnet50_v1 --data-shape 512 --batch-size 4

Traceback (most recent call last):
  File "train_ssd.py", line 253, in <module>
    train(net, train_data, val_data, eval_metric, args)
  File "train_ssd.py", line 185, in train
    for i, batch in enumerate(train_data):
  File "/root/miniconda3/envs/gluon/lib/python3.6/site-packages/mxnet/gluon/data/dataloader.py", line 217, in __next__
    idx, batch = self._data_queue.get()
  File "/root/miniconda3/envs/gluon/lib/python3.6/multiprocessing/queues.py", line 344, in get
    return _ForkingPickler.loads(res)
  File "/root/miniconda3/envs/gluon/lib/python3.6/site-packages/mxnet/gluon/data/dataloader.py", line 55, in rebuild_ndarray
    fd = fd.detach()
  File "/root/miniconda3/envs/gluon/lib/python3.6/multiprocessing/resource_sharer.py", line 57, in detach
    with _resource_sharer.get_connection(self._id) as conn:
  File "/root/miniconda3/envs/gluon/lib/python3.6/multiprocessing/resource_sharer.py", line 87, in get_connection
    c = Client(address, authkey=process.current_process().authkey)
  File "/root/miniconda3/envs/gluon/lib/python3.6/multiprocessing/connection.py", line 487, in Client
    c = SocketClient(address)
  File "/root/miniconda3/envs/gluon/lib/python3.6/multiprocessing/connection.py", line 614, in SocketClient
    s.connect(address)
ConnectionRefusedError: [Errno 111] Connection refused

**Comment by zhreshold** [comment]
It's actually the same for #215 
I am looking into this. In the mean time you can use a smaller num_workers by specifying `-j 2` for example.

**Comment by zhaoxin111** [comment]
@zhreshold  
It works when I set the num_works = 0 . In addition, my OS is ubantu 14.
Thank you!
