### ISSUE TITLE
cannot import name 'SimpleQueue' when running demo_ssd.py

### ISSUE THREAD

**Issue by guanlinting** [dmlc/gluon-cv#235]
mxnet-cu91         1.2.1
gluoncv                0.3.0
python                 3.6.5
os                        windows 10 

Traceback (most recent call last):
  File "demo_ssd.py", line 5, in <module>
    import gluoncv as gcv
  File "C:\Users\bonobo\AppData\Roaming\Python\Python36\site-packages\gluoncv-0.3.0-py3.6.egg\gluoncv\__init__.py", line 7, in <module>
  File "C:\Users\bonobo\AppData\Roaming\Python\Python36\site-packages\gluoncv-0.3.0-py3.6.egg\gluoncv\data\__init__.py", line 7, in <module>
  File "C:\Users\bonobo\AppData\Roaming\Python\Python36\site-packages\gluoncv-0.3.0-py3.6.egg\gluoncv\data\dataloader.py", line 9, in <module>
ImportError: cannot import name 'SimpleQueue'

**Comment by WHCer** [comment]
you have to compile from the newest mxnet master which include SimpleQueue. I try it serval days ago,
mx.__version__ = '1.3.0'

**Comment by ewinterrms** [comment]
you are referring to the nightly builds/pre-release?  I've been using pip install --pre mxnet, but are you suggesting to pull the nightly mxnet master and compile instead?  Also, same for mxnet and mxnet-cu90?

Thanks for the help!  I'm having the same problem and hoping I might skip some troubleshooting with your suggestions.

**Comment by zhreshold** [comment]
I have moved the dependency into runtime, now with gluon-cv master it won't require 1.3 for SSD training any more.
Let me know if any of you still getting the error.
