### ISSUE TITLE
FRCNNAttributeError: module 'mxnet.symbol' has no attribute 'shape_array'

### ISSUE THREAD

**Issue by yunfanLu** [dmlc/gluon-cv#239]
```
[yunfan.lu@yz-gpu029 gluon-cv]$ MXNET_CUDNN_AUTOTUNE_DEFAULT=0 python ../gluon-cv/scripts/detection/faster_rcnn/train_faster_rcnn.py --gpus 0,1,2,3 --dataset voc --network resnet50_v1b
/data/yunfan.lu/App/github.data/GluonCV-Project/GluonCV/gluon-cv/mxnet/gluon/block.py:413: UserWarning: load_params is deprecated. Please use load_parameters.
  warnings.warn("load_params is deprecated. Please use load_parameters.")
INFO:root:Namespace(batch_size=4, dataset='voc', epochs=30, gpus='0,1,2,3', log_interval=100, lr=0.001, lr_decay=0.1, lr_decay_epoch='14,20', momentum=0.9, network='resnet50_v1b', num_workers=8, resume='', save_interval=1, save_prefix='faster_rcnn_resnet50_v1b_voc', seed=233, start_epoch=0, val_interval=1, verbose=False, wd=0.0005)
INFO:root:Start training from [Epoch 0]
Traceback (most recent call last):
  File "../gluon-cv/scripts/detection/faster_rcnn/train_faster_rcnn.py", line 398, in <module>
    train(net, train_data, val_data, eval_metric, args)
  File "../gluon-cv/scripts/detection/faster_rcnn/train_faster_rcnn.py", line 312, in train
    cls_pred, box_pred, roi, samples, matches, rpn_score, rpn_box, anchors = net(data, gt_box)
  File "/data/yunfan.lu/App/github.data/GluonCV-Project/GluonCV/gluon-cv/mxnet/gluon/block.py", line 533, in __call__
    out = self.forward(*args)
  File "/data/yunfan.lu/App/github.data/GluonCV-Project/GluonCV/gluon-cv/mxnet/gluon/block.py", line 888, in forward
    return self._call_cached_op(x, *args)
  File "/data/yunfan.lu/App/github.data/GluonCV-Project/GluonCV/gluon-cv/mxnet/gluon/block.py", line 778, in _call_cached_op
    self._build_cache(*args)
  File "/data/yunfan.lu/App/github.data/GluonCV-Project/GluonCV/gluon-cv/mxnet/gluon/block.py", line 730, in _build_cache
    data, out = self._get_graph(*args)
  File "/data/yunfan.lu/App/github.data/GluonCV-Project/GluonCV/gluon-cv/mxnet/gluon/block.py", line 722, in _get_graph
    out = self.hybrid_forward(symbol, *grouped_inputs, **params)  # pylint: disable=no-value-for-parameter
  File "/data/yunfan.lu/App/github.data/GluonCV-Project/GluonCV/gluon-cv/gluoncv/model_zoo/faster_rcnn/faster_rcnn.py", line 198, in hybrid_forward
    self.rpn(feat, F.zeros_like(x))
  File "/data/yunfan.lu/App/github.data/GluonCV-Project/GluonCV/gluon-cv/mxnet/gluon/block.py", line 533, in __call__
    out = self.forward(*args)
  File "/data/yunfan.lu/App/github.data/GluonCV-Project/GluonCV/gluon-cv/mxnet/gluon/block.py", line 905, in forward
    return self.hybrid_forward(symbol, x, *args, **params)
  File "/data/yunfan.lu/App/github.data/GluonCV-Project/GluonCV/gluon-cv/gluoncv/model_zoo/rpn/rpn.py", line 101, in hybrid_forward
    anchors, rpn_scores, F.stop_gradient(rpn_box_pred), img)
  File "/data/yunfan.lu/App/github.data/GluonCV-Project/GluonCV/gluon-cv/mxnet/gluon/block.py", line 533, in __call__
    out = self.forward(*args)
  File "/data/yunfan.lu/App/github.data/GluonCV-Project/GluonCV/gluon-cv/mxnet/gluon/block.py", line 905, in forward
    return self.hybrid_forward(symbol, x, *args, **params)
  File "/data/yunfan.lu/App/github.data/GluonCV-Project/GluonCV/gluon-cv/gluoncv/model_zoo/rpn/proposal.py", line 68, in hybrid_forward
    roi = self._clipper(roi, img)
  File "/data/yunfan.lu/App/github.data/GluonCV-Project/GluonCV/gluon-cv/mxnet/gluon/block.py", line 533, in __call__
    out = self.forward(*args)
  File "/data/yunfan.lu/App/github.data/GluonCV-Project/GluonCV/gluon-cv/mxnet/gluon/block.py", line 905, in forward
    return self.hybrid_forward(symbol, x, *args, **params)
  File "/data/yunfan.lu/App/github.data/GluonCV-Project/GluonCV/gluon-cv/gluoncv/nn/bbox.py", line 221, in hybrid_forward
    window = F.shape_array(img).slice_axis(axis=0, begin=2, end=None).expand_dims(0)
AttributeError: module 'mxnet.symbol' has no attribute 'shape_array'
```

```
[yunfan.lu@yz-gpu029 gluon-cv]$ python
Python 3.6.5 |Anaconda, Inc.| (default, Apr 29 2018, 16:14:56)
[GCC 7.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import mxnet
>>> mxnet.__version__
'1.3.0'
>>> exit()
```

Thanks for your attentation.

**Comment by yunfanLu** [comment]
the `shape_array ` is a function of ndarray.

https://mxnet.incubator.apache.org/search.html?q=shape_array&check_keywords=yes&area=default

**Comment by zhreshold** [comment]
shape_array is merged 1 month ago, so make sure mxnet is latest.

**Comment by yunfanLu** [comment]
Thank you very much !
