### ISSUE TITLE
IndexError: too many indices for array

### ISSUE THREAD

**Issue by Bishopxu** [dmlc/gluon-cv#363]
When using my own data to train object detection, I encountered the following problems:

INFO:root:[Epoch 0][Batch 70], Speed: 31.068 samples/sec, CrossEntropy=5.312, SmoothL1=2.137
INFO:root:[Epoch 0][Batch 71], Speed: 30.860 samples/sec, CrossEntropy=5.291, SmoothL1=2.138
INFO:root:[Epoch 0][Batch 72], Speed: 30.140 samples/sec, CrossEntropy=5.271, SmoothL1=2.131
Process Process-2:
Traceback (most recent call last):
  File "/usr/lib/python3.5/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/usr/lib/python3.5/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/root/.virtualenvs/migu/lib/python3.5/site-packages/mxnet/gluon/data/dataloader.py", line 169, in worker_loop
    batch = batchify_fn([dataset[i] for i in samples])
  File "/root/.virtualenvs/migu/lib/python3.5/site-packages/mxnet/gluon/data/dataloader.py", line 169, in <listcomp>
    batch = batchify_fn([dataset[i] for i in samples])
  File "/root/.virtualenvs/migu/lib/python3.5/site-packages/mxnet/gluon/data/dataset.py", line 133, in __getitem__
    return self._fn(*item)
  File "/root/.virtualenvs/migu/lib/python3.5/site-packages/gluoncv/data/transforms/presets/ssd.py", line 153, in __call__
    bbox, crop = experimental.bbox.random_crop_with_constraints(bbox, (w, h))
  File "/root/.virtualenvs/migu/lib/python3.5/site-packages/gluoncv/data/transforms/experimental/bbox.py", line 99, in random_crop_with_constraints
    new_bbox = bbox_crop(bbox, crop, allow_outside_center=False)
  File "/root/.virtualenvs/migu/lib/python3.5/site-packages/gluoncv/data/transforms/bbox.py", line 51, in crop
    centers = (bbox[:, :2] + bbox[:, 2:4]) / 2
IndexError: too many indices for array

INFO:root:[Epoch 0][Batch 9], Speed: 28.705 samples/sec, CrossEntropy=9.913, SmoothL1=2.756
INFO:root:[Epoch 0][Batch 19], Speed: 27.866 samples/sec, CrossEntropy=8.206, SmoothL1=2.453
Process Process-2:
Traceback (most recent call last):
  File "/usr/lib/python3.5/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/usr/lib/python3.5/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/root/.virtualenvs/migu/lib/python3.5/site-packages/mxnet/gluon/data/dataloader.py", line 169, in worker_loop
    batch = batchify_fn([dataset[i] for i in samples])
  File "/root/.virtualenvs/migu/lib/python3.5/site-packages/mxnet/gluon/data/dataloader.py", line 169, in <listcomp>
    batch = batchify_fn([dataset[i] for i in samples])
  File "/root/.virtualenvs/migu/lib/python3.5/site-packages/mxnet/gluon/data/dataset.py", line 133, in __getitem__
    return self._fn(*item)
  File "/root/.virtualenvs/migu/lib/python3.5/site-packages/gluoncv/data/transforms/presets/ssd.py", line 147, in __call__
    bbox = tbbox.translate(label, x_offset=expand[0], y_offset=expand[1])
  File "/root/.virtualenvs/migu/lib/python3.5/site-packages/gluoncv/data/transforms/bbox.py", line 160, in translate
    bbox[:, :2] += (x_offset, y_offset)
IndexError: too many indices for array

The custom dataset are fully complied with the Pascal VOC object detection format. I tried to take only a portion of the data for training(1000 images) and it works fine. But when using all the data(5000 images), there will be a problem with IndexError. I have carefully checked the data and labels. Running on keras-retinanet(https://github.com/fizyr/keras-retinanet) is also completely correct(5000 images). Hope to get help...

**Comment by zhreshold** [comment]
@Bishopxu Can you add a try catch block around https://github.com/dmlc/gluon-cv/blob/master/gluoncv/data/transforms/bbox.py#L160 and print the bbox if the IndexError raises?

This will help us to diagnose faster, thanks

**Comment by Bishopxu** [comment]
Based on your suggestion, I found the cause of the error, the same as [https://github.com/dmlc/gluon-cv/issues/267](url)
Thank you!
