### ISSUE TITLE
GLUON-CV Finetune Tutorial Error

### ISSUE THREAD

**Issue by lsabi** [dmlc/gluon-cv#443]
Hello everyone,

I started following the tutorial [8. Finetune a pretrained detection model](https://gluon-cv.mxnet.io/build/examples_detection/finetune_detection.html) of the gluon-cv official site. I have the following packages installed on my Kubuntu 18.04 64-bit laptop:

> gluoncv (0.4.0b20181019)
> mxnet-mkl (1.3.1b20181024)

So, I downloaded the full python script (not the anaconda script) and found the following errors/bugs:

## BUG 1:
When run, it says that it cannot find the network. Following the output I got.

`label: [[309.6292  205.79944 355.75494 274.14044   0.     ]]

Traceback (most recent call last):
  File "finetune_detection.py", line 62, in <module>
    pretrained_base=False, transfer='voc')
  File "/home/user/.local/lib/python3.6/site-packages/gluoncv/model_zoo/model_zoo.py", line 186, in get_model
    net = _models[name](**kwargs)
  File "/home/user/.local/lib/python3.6/site-packages/gluoncv/model_zoo/ssd/ssd.py", line 809, in ssd_512_mobilenet1_0_custom
    net = get_model('ssd_512_mobilenet1_0_' + str(transfer), pretrained=True, **kwargs)
  File "/home/user/.local/lib/python3.6/site-packages/gluoncv/model_zoo/model_zoo.py", line 185, in get_model
    raise ValueError(err_str)
ValueError: "ssd_512_mobilenet1_0_voc" is not among the following model list:`

**NOTE:**
- There was also the list of networks, which I omitted for space's sake.
- I anonymized the user
- I'm running Kubuntu 18.04

The problem is that the get_model function changes the name of the base model, in order to do transfer learning, such that the dots are removed (and the name of the example network contains a dot). Thus the network is not found (even though the name passed as parameter is correct).

Example: 
net = gcv.model_zoo.get_model('ssd_512_mobilenet1.0_custom', classes=classes, pretrained_base=False, transfer='voc')

Downloads the network ssd_512_mobilenet1.0_custom, but then transfers from the network ssd_512_mobilenet1_0_voc (which does not exist). The only solution, is to comment this line and use the previous get_model function (at line 50, which then resets the classes at line 54).

## BUG 2:
I have to mention that I installed mxnet-mkl (with the command: `pip3 install --pre mxnet-mkl`, version 1.3.1) since I have an Intel CPU and gluon-cv (with the command: `pip3 install --pre gluoncv`).

When I run the script (after using a temporary fix to the above bug), I get the following output:

`label: [[309.6292  205.79944 355.75494 274.14044   0.     ]]
[17:22:36] src/imperative/./imperative_utils.h:90: GPU support is disabled. Compile MXNet with USE_CUDA=1 to enable GPU support.

[17:22:36] src/operator/nn/mkldnn/mkldnn_base.cc:74: Allocate 8192 bytes with malloc directly

[17:22:36] src/operator/nn/mkldnn/mkldnn_base.cc:74: Allocate 32768 bytes with malloc directly

[17:22:36] src/operator/nn/mkldnn/mkldnn_base.cc:74: Allocate 9437184 bytes with malloc directly

python3: malloc.c:4023: _int_malloc: Assertion `(unsigned long) (size) >= (unsigned long) (nb)' failed.

Aborted (core dumped)
`

I have no clue why it only works with the GPU, but the error should be raised at line 97 (though I'm not sure):
`try:
    a = mx.nd.zeros((1,), ctx=mx.gpu(0))
    ctx = [mx.gpu(0)]
except:
    ctx = [mx.cpu()]`

I also checked, and the flow actually falls in the except block, updating the ctx, but it seems that the error goes on. I would like to provide a solution or at least the line that causes the error, but I have no clue where the problem could lie.

Thanks.

**Comment by zhreshold** [comment]
@lsabi It works with CPU, the CI is running using GPU but it will fall back to CPU once gpu is not found. 
I have double checked it will run with gluoncv 0.4.0b20181101 and mxnet 1.3.0, please check if you are messing with anaconda python/pip which might cause different version of gluoncv to be used.

**Comment by lsabi** [comment]
@zhreshold Hi, I reverted back to mxnet 1.3.1 (no mkl version) and it works, no more errors. Though it takes a life to train even simple models.
Thanks anyway
