### ISSUE TITLE
train_ssd.py super(type, obj): obj must be an instance or subtype of type

### ISSUE THREAD

**Issue by engineer1982** [dmlc/gluon-cv#520]
Hi there

when I try to run the train_ssd.py I get the following error:

===========================
runfile('C:/Users/Valeadmin/Documents/Python Scripts/26_gluoncv_SSD_objdetect/train_ssd.py', wdir='C:/Users/Valeadmin/Documents/Python Scripts/26_gluoncv_SSD_objdetect')
Traceback (most recent call last):

  File "<ipython-input-102-4e58b5d0c72e>", line 1, in <module>
    runfile('C:/Users/Valeadmin/Documents/Python Scripts/26_gluoncv_SSD_objdetect/train_ssd.py', wdir='C:/Users/Valeadmin/Documents/Python Scripts/26_gluoncv_SSD_objdetect')

  File "C:\Users\Valeadmin\Anaconda3\envs\mxnet\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 704, in runfile
    execfile(filename, namespace)

  File "C:\Users\Valeadmin\Anaconda3\envs\mxnet\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 108, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "C:/Users/Valeadmin/Documents/Python Scripts/26_gluoncv_SSD_objdetect/train_ssd.py", line 248, in <module>
    train_dataset, val_dataset, eval_metric = get_dataset(args.dataset, args)

  File "C:/Users/Valeadmin/Documents/Python Scripts/26_gluoncv_SSD_objdetect/train_ssd.py", line 72, in get_dataset
    splits=[(2007, 'trainval'), (2012, 'trainval')])

  File "C:\Users\Valeadmin\Anaconda3\envs\mxnet\lib\site-packages\gluoncv\data\pascal_voc\detection.py", line 50, in __init__
    super(VOCDetection, self).__init__(root)

TypeError: super(type, obj): obj must be an instance or subtype of type
===========================

Does anyone know whats going on?

Thanks

**Comment by zhreshold** [comment]
Can you try update gluoncv and mxnet, the error is something pretty weird and might relate to your locla configuation.
