### ISSUE TITLE
train yolo3 error

### ISSUE THREAD

**Issue by xizi** [dmlc/gluon-cv#551]
INFO:root:Namespace(batch_size=64, data_shape=416, dataset='voc', epochs=200, gpus='0,1,2', label_smooth=False, log_interval=100, lr=0.001, lr_decay=0.1, lr_decay_epoch='160,180', lr_decay_period=0, lr_mode='step', mixup=False, momentum=0.9, network='darknet53', no_mixup_epochs=20, no_random_shape=False, no_wd=False, num_samples=16551, num_workers=4, resume='', save_interval=10, save_prefix='yolo3_darknet53_voc', seed=233, start_epoch=0, syncbn=True, val_interval=1, warmup_epochs=0, warmup_lr=0.0, wd=0.0005)
INFO:root:Start training from [Epoch 0]
Traceback (most recent call last):
  File "train_yolo3.py", line 330, in <module>
    train(net, train_data, val_data, eval_metric, ctx, args)
  File "train_yolo3.py", line 244, in train
    for i, batch in enumerate(train_data):
  File "build/bdist.linux-x86_64/egg/gluoncv/data/dataloader.py", line 273, in __iter__
  File "build/bdist.linux-x86_64/egg/gluoncv/data/dataloader.py", line 150, in __init__
TypeError: __init__() got an unexpected keyword argument 'prefetch'
Exception AttributeError: "'_RandomTransformMultiWorkerIter' object has no attribute '_shutdown'" in <bound method _RandomTransformMultiWorkerIter.__del__ of <gluoncv.data.dataloader._RandomTransformMultiWorkerIter object at 0x7f542156de90>> ignored

**Comment by zhreshold** [comment]
Please update mxnet to nightly build

**Comment by xizi** [comment]
@zhreshold train_yolo3.py中训练图片的尺寸 w == h，但在demo_yolo.py中测试时，图片的尺寸为什么保持原始图片比例而不强制resize成 w == h呢？理论上是不是在测试时保持图片的大小及比例与训练时一致检测性能更好？

**Comment by gaobb** [comment]
> INFO:root:Namespace(batch_size=64, data_shape=416, dataset='voc', epochs=200, gpus='0,1,2', label_smooth=False, log_interval=100, lr=0.001, lr_decay=0.1, lr_decay_epoch='160,180', lr_decay_period=0, lr_mode='step', mixup=False, momentum=0.9, network='darknet53', no_mixup_epochs=20, no_random_shape=False, no_wd=False, num_samples=16551, num_workers=4, resume='', save_interval=10, save_prefix='yolo3_darknet53_voc', seed=233, start_epoch=0, syncbn=True, val_interval=1, warmup_epochs=0, warmup_lr=0.0, wd=0.0005)
> INFO:root:Start training from [Epoch 0]
> Traceback (most recent call last):
> File "train_yolo3.py", line 330, in 
> train(net, train_data, val_data, eval_metric, ctx, args)
> File "train_yolo3.py", line 244, in train
> for i, batch in enumerate(train_data):
> File "build/bdist.linux-x86_64/egg/gluoncv/data/dataloader.py", line 273, in **iter**
> File "build/bdist.linux-x86_64/egg/gluoncv/data/dataloader.py", line 150, in **init**
> TypeError: **init**() got an unexpected keyword argument 'prefetch'
> Exception AttributeError: "'_RandomTransformMultiWorkerIter' object has no attribute '_shutdown'" in <bound method _RandomTransformMultiWorkerIter.**del** of <gluoncv.data.dataloader._RandomTransformMultiWorkerIter object at 0x7f542156de90>> ignored

hi, I also meet the same issue and I want to know how to fix it.

**Comment by zhreshold** [comment]
@xizi Evaluation image size is fixed, while demo is more relaxed to whatever input size is.
