### ISSUE TITLE
ssd example error:  __init__() got an unexpected keyword argument 'norm_layer'

### ISSUE THREAD

**Issue by aaronmarkham** [dmlc/gluon-cv#678]
I'm running the example here: https://gluon-cv.mxnet.io/build/examples_detection/train_ssd_voc.html#train-ssd-on-pascal-voc-dataset
I'm using MXNet 1.4.0 from a mxnet-cu92 pip install + a gluoncv pip install, both from today.

I tried:
```
python train_ssd.py --gpus 0,1,2,3,4,5,6,7 --network resnet50_v1 --data-shape 512
python train_ssd.py --gpus 0,1,2,3 --network resnet50_v1 --data-shape 512
python train_ssd.py
```
They all get the same error:
```
$ python train_ssd.py
Traceback (most recent call last):
  File "train_ssd.py", line 246, in <module>
    net = get_model(net_name, pretrained_base=True, norm_layer=gluon.nn.BatchNorm)
  File "/home/ubuntu/anaconda3/envs/mxnet_p36/lib/python3.6/site-packages/gluoncv/model_zoo/model_zoo.py", line 186, in get_model
    net = _models[name](**kwargs)
  File "/home/ubuntu/anaconda3/envs/mxnet_p36/lib/python3.6/site-packages/gluoncv/model_zoo/ssd/ssd.py", line 327, in ssd_300_vgg16_atrous_voc
    pretrained_base=pretrained_base, **kwargs)
  File "/home/ubuntu/anaconda3/envs/mxnet_p36/lib/python3.6/site-packages/gluoncv/model_zoo/ssd/ssd.py", line 298, in get_ssd
    pretrained=pretrained_base, classes=classes, ctx=ctx, **kwargs)
  File "/home/ubuntu/anaconda3/envs/mxnet_p36/lib/python3.6/site-packages/gluoncv/model_zoo/ssd/ssd.py", line 103, in __init__
    super(SSD, self).__init__(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'norm_layer'
```

**Comment by 1453042287** [comment]
i meet the same problem but when i change my python's version to 3.5, it works fine

**Comment by tlind** [comment]
Same problem here with train_yolo3.py, Python 2.7, and the latest nightly mxnet-cu90 build of v1.5.0 when using multiple GPUs with syncbn=true (with false, it works fine)...

**Comment by zhreshold** [comment]
Using training script from master requires gluoncv master build. 
So you will need to upgrade gluoncv:
```bash
pip install gluoncv --pre --upgrade
```

**Comment by jamiechoi1995** [comment]
I tried with python3 and update gluoncv master build, does not work for me.
