### ISSUE TITLE
Cannot download ssd_512_mobilenet1.0_voc_int8

### ISSUE THREAD

**Issue by stereomatchingkiss** [dmlc/gluon-cv#704]
os : win64
gluoncv version : 0.5

```
import gluoncv as gcv
from gluoncv.utils import export_block

gcv.model_zoo.get_model("ssd_512_mobilenet1.0_voc_int8", pretrained=True)

```

Error message

```
Traceback (most recent call last):
  File "download_model.py", line 4, in <module>
    gcv.model_zoo.get_model("ssd_512_mobilenet1.0_voc_int8", pretrained=True)
  File "C:\Users\yyyy\Anaconda3\envs\gluoncv\lib\site-packages\gluoncv\model_zoo\model_zoo.py", line 231, in get_model
    net = _models[name](**kwargs)
  File "C:\Users\yyyy\Anaconda3\envs\gluoncv\lib\site-packages\gluoncv\model_zoo\quantized\quantized.py", line 45, in func
    sym_net = SymbolBlock.imports(json_file, ['data'], None, ctx=ctx)
  File "C:\Users\yyyy\Anaconda3\envs\gluoncv\lib\site-packages\mxnet\gluon\block.py", line 1018, in imports
    sym = symbol.load(symbol_file)
  File "C:\Users\yyyy\Anaconda3\envs\gluoncv\lib\site-packages\mxnet\symbol\symbol.py", line 2620, in load
    check_call(_LIB.MXSymbolCreateFromFile(c_str(fname), ctypes.byref(handle)))
  File "C:\Users\yyyy\Anaconda3\envs\gluoncv\lib\site-packages\mxnet\base.py", line 252, in check_call
    raise MXNetError(py_str(_LIB.MXGetLastError()))
mxnet.base.MXNetError: [10:54:35] C:\Jenkins\workspace\mxnet-tag\mxnet\3rdparty\dmlc-core\src\io\local_filesys.cc:199: Check failed: allow_null  LocalFileSystem::Open "C:\Users\yyyy\Anaconda3\envs\gluoncv\lib\site-packages\gluoncv\model_zoo\quantized\ssd_512_mobilenet1.0_voc_int8-symbol.json": No such file or directory
```

**Comment by zhreshold** [comment]
There was a problem with pip package, please update gluoncv again, the latest version is 0.4.0.post0

**Comment by pengzhao-intel** [comment]
@stereomatchingkiss could you try again?

**Comment by stereomatchingkiss** [comment]
Try again after install gluoncv 0.5.0b20190327, mxnet-cu92mkl  1.4.0.post0

Error messages : 

```
File "download_model.py", line 4, in <module>
    gcv.model_zoo.get_model("ssd_512_mobilenet1.0_voc_int8", pretrained=True)
  File "C:\Users\yyyy\Anaconda3\envs\gluoncv\lib\site-packages\gluoncv\model_zoo\model_zoo.py", line 231, in get_model
    net = _models[name](**kwargs)
  File "C:\Users\yyyy\Anaconda3\envs\gluoncv\lib\site-packages\gluoncv\model_zoo\quantized\quantized.py", line 45, in func
    sym_net = SymbolBlock.imports(json_file, ['data'], None, ctx=ctx)
  File "C:\Users\yyyy\Anaconda3\envs\gluoncv\lib\site-packages\mxnet\gluon\block.py", line 1018, in imports
    sym = symbol.load(symbol_file)
  File "C:\Users\yyyy\Anaconda3\envs\gluoncv\lib\site-packages\mxnet\symbol\symbol.py", line 2620, in load
    check_call(_LIB.MXSymbolCreateFromFile(c_str(fname), ctypes.byref(handle)))
  File "C:\Users\yyyy\Anaconda3\envs\gluoncv\lib\site-packages\mxnet\base.py", line 252, in check_call
    raise MXNetError(py_str(_LIB.MXGetLastError()))
mxnet.base.MXNetError: Failed loading Op data_quantize of type _contrib_quantize_v2: [10:39:07] C:\Jenkins\workspace\mxnet-tag\mxnet\3rdparty\tvm\nnvm\src\core\op.cc:55: Check failed: op != nullptr Operator _contrib_quantize_v2 is not registered
```

**Comment by xinyu-intel** [comment]
@stereomatchingkiss please try gluoncv==0.4.0.post0 and mxnet-cu92mkl nightly build version
