### ISSUE TITLE
The mobilenet1_0 and mobilenet1.0 naming inconsistencies caused download bugs.

### ISSUE THREAD

**Issue by becauseofAI** [dmlc/gluon-cv#709]
The pretrained models of mobilenet  were named **xx_mobilenet1.0_xx** in ```model_store.py```. But the input name of many programs needs to be **xx_mobilenet1_0_xx**. So the provided dict. key can't match the existent dict. key when downloading the pretrained models. 

An error example from this [issue](https://github.com/becauseofAI/MobileFace/issues/5#issuecomment-477505307) as follow:
```
Try to use gluon to downdload yolo3_mobilenet1.0_voc below:
model_zoo.get_model('yolo3_mobilenet1.0_voc', pretrained=True)

It has an error: of Pretrained model for yolo3_mobilenet1_0_voc is not available as below:

Traceback (most recent call last):
File "./demo_webcam.py", line 9, in 
net = gcv.model_zoo.get_model('yolo3_mobilenet1.0_voc', pretrained=True)
File "build/bdist.linux-aarch64/egg/gluoncv/model_zoo/model_zoo.py", line 201, in get_model
File "build/bdist.linux-aarch64/egg/gluoncv/model_zoo/yolo/yolo3.py", line 630, in yolo3_mobilenet1_0_voc
File "build/bdist.linux-aarch64/egg/gluoncv/model_zoo/yolo/yolo3.py", line 476, in get_yolov3
File "build/bdist.linux-aarch64/egg/gluoncv/model_zoo/model_store.py", line 138, in get_model_file
File "build/bdist.linux-aarch64/egg/gluoncv/model_zoo/model_store.py", line 108, in short_hash
ValueError: Pretrained model for yolo3_mobilenet1_0_voc is not available.
```

**Comment by zhreshold** [comment]
can you double check agian? It seems working fine from my side
