### ISSUE TITLE
cudaMalloc failed: out of memory training YOLOv3

### ISSUE THREAD

**Issue by omaralvarez** [dmlc/gluon-cv#798]
Ubuntu 18.04 - CUDA 10 - RTX 2070 - gluoncv==0.5.0b20190606 - mxnet-cu100==1.4.1

I am trying to train YOLOv3, but I am getting the following error (default parameters):

```
INFO:root:Namespace(batch_size=64, data_shape=416, dataset='voc', epochs=200, gpus='0', label_smooth=False, log_interval=100, lr=0.001, lr_decay=0.1, lr_decay_epoch='160,180', lr_decay_period=0, lr_mode='step', mixup=False, momentum=0.9, network='darknet53', no_mixup_epochs=20, no_random_shape=False, no_wd=False, num_samples=16551, num_workers=4, resume='', save_interval=10, save_prefix='yolo3_darknet53_voc', seed=233, start_epoch=0, syncbn=False, val_interval=1, warmup_epochs=0, warmup_lr=0.0, wd=0.0005)
INFO:root:Start training from [Epoch 0]
[14:54:30] src/operator/nn/./cudnn/./cudnn_algoreg-inl.h:97: Running performance tests to find the best convolution algorithm, this can take a while... (setting env variable MXNET_CUDNN_AUTOTUNE_DEFAULT to 0 to disable)
Traceback (most recent call last):
  File "train_yolo3.py", line 333, in <module>
    train(net, train_data, val_data, eval_metric, ctx, args)
  File "train_yolo3.py", line 269, in train
    obj_metrics.update(0, obj_losses)
  File "/home/omaralv/.virtualenvs/gluon-yolo/lib/python3.6/site-packages/mxnet/metric.py", line 1289, in update
    self.sum_metric += ndarray.sum(pred).asscalar()
  File "/home/omaralv/.virtualenvs/gluon-yolo/lib/python3.6/site-packages/mxnet/ndarray/ndarray.py", line 1998, in asscalar
    return self.asnumpy()[0]
  File "/home/omaralv/.virtualenvs/gluon-yolo/lib/python3.6/site-packages/mxnet/ndarray/ndarray.py", line 1980, in asnumpy
    ctypes.c_size_t(data.size)))
  File "/home/omaralv/.virtualenvs/gluon-yolo/lib/python3.6/site-packages/mxnet/base.py", line 252, in check_call
    raise MXNetError(py_str(_LIB.MXGetLastError()))
mxnet.base.MXNetError: [14:54:30] src/storage/./pooled_storage_manager.h:151: cudaMalloc failed: out of memory

Stack trace returned 10 entries:
[bt] (0) /home/omaralv/.virtualenvs/gluon-yolo/lib/python3.6/site-packages/mxnet/libmxnet.so(+0x4114ba) [0x7f69b3f6c4ba]
[bt] (1) /home/omaralv/.virtualenvs/gluon-yolo/lib/python3.6/site-packages/mxnet/libmxnet.so(+0x411ad1) [0x7f69b3f6cad1]
[bt] (2) /home/omaralv/.virtualenvs/gluon-yolo/lib/python3.6/site-packages/mxnet/libmxnet.so(+0x342dc6b) [0x7f69b6f88c6b]
[bt] (3) /home/omaralv/.virtualenvs/gluon-yolo/lib/python3.6/site-packages/mxnet/libmxnet.so(+0x343217f) [0x7f69b6f8d17f]
[bt] (4) /home/omaralv/.virtualenvs/gluon-yolo/lib/python3.6/site-packages/mxnet/libmxnet.so(+0x379c9ad) [0x7f69b72f79ad]
[bt] (5) /home/omaralv/.virtualenvs/gluon-yolo/lib/python3.6/site-packages/mxnet/libmxnet.so(+0x378d14c) [0x7f69b72e814c]
[bt] (6) /home/omaralv/.virtualenvs/gluon-yolo/lib/python3.6/site-packages/mxnet/libmxnet.so(+0x378d5cb) [0x7f69b72e85cb]
[bt] (7) /home/omaralv/.virtualenvs/gluon-yolo/lib/python3.6/site-packages/mxnet/libmxnet.so(+0x378e933) [0x7f69b72e9933]
[bt] (8) /home/omaralv/.virtualenvs/gluon-yolo/lib/python3.6/site-packages/mxnet/libmxnet.so(+0x378f9ac) [0x7f69b72ea9ac]
[bt] (9) /home/omaralv/.virtualenvs/gluon-yolo/lib/python3.6/site-packages/mxnet/libmxnet.so(+0x3795cc1) [0x7f69b72f0cc1]
```
I have tried less batch size, but even a batch size of 8 is not working. I have used also --no-random-shape to no avail. I can train YOLOv3 using darknet with no issue and higher batch size. 

Is this normal? How much VRAM does one need to train YOLO?

**Comment by zhreshold** [comment]
single card with 8G memory is quite limiting, you can try data-shape fixed at 320, batch-size 8, you can even use mobilenet version to reduce the memory.
As far as I know, the true batchsize in darknet is batchsize/subdivision.

**Comment by omaralvarez** [comment]
Can you tune internal YOLO parameters like subdivision?

**Comment by zhreshold** [comment]
you are free to modify anchors, but for subdivision, it is not implemented yet, but can be added quickly by dividing the data before calling forward/backward

**Comment by omaralvarez** [comment]
Thanks for your help, I'm not experienced using Gluon, how would one do that more or less? For now I have modified train_yolov3.py to train with a custom dataset, but that is it for now. I would love to also add to that script the subdivision code, but I am a litlle lost there.

**Comment by steinmann** [comment]
> you are free to modify anchors, but for subdivision, it is not implemented yet, but can be added quickly by dividing the data before calling forward/backward

How would you do this? The way YOLO3DefaultTrainTransform and YOLOV3PrefetchTargetGenerator work together is rather confusing to me. Any help would be greatly appreciated.
