### ISSUE TITLE
AssertionError: HybridBlock requires the first argument to forward be either Symbol or NDArray, but got <class 'PIL.Image.Image'>

### ISSUE THREAD

**Issue by dgks0n** [dmlc/gluon-cv#810]
I am trying to test the pre-trained PSP model is `psp_resnet101_citys` with cityscapes databset but I got below error, I don't know how to solve. Can someone give me a hotfix?

```
0%|                                                                                                                                                                                     | 0/3475 [00:00<?, ?it/s]multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/v2m/anaconda3/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/home/v2m/anaconda3/envs/my_env3/lib/python3.7/site-packages/mxnet/gluon/data/dataloader.py", line 400, in _worker_fn
    batch = batchify_fn([_worker_dataset[i] for i in samples])
  File "/home/v2m/anaconda3/envs/my_env3/lib/python3.7/site-packages/mxnet/gluon/data/dataloader.py", line 400, in <listcomp>
    batch = batchify_fn([_worker_dataset[i] for i in samples])
  File "/home/v2m/anaconda3/envs/my_env3/lib/python3.7/site-packages/gluoncv/data/cityscapes.py", line 52, in __getitem__
    img = self.transform(img)
  File "/home/v2m/anaconda3/envs/my_env3/lib/python3.7/site-packages/mxnet/gluon/block.py", line 540, in __call__
    out = self.forward(*args)
  File "/home/v2m/anaconda3/envs/my_env3/lib/python3.7/site-packages/mxnet/gluon/nn/basic_layers.py", line 53, in forward
    x = block(x)
  File "/home/v2m/anaconda3/envs/my_env3/lib/python3.7/site-packages/mxnet/gluon/block.py", line 540, in __call__
    out = self.forward(*args)
  File "/home/v2m/anaconda3/envs/my_env3/lib/python3.7/site-packages/mxnet/gluon/block.py", line 921, in forward
    "Symbol or NDArray, but got %s"%type(x)
AssertionError: HybridBlock requires the first argument to forward be either Symbol or NDArray, but got <class 'PIL.Image.Image'>
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "test.py", line 81, in <module>
    test(args)
  File "test.py", line 59, in test
    for i, (data, dsts) in enumerate(tbar):
  File "/home/v2m/anaconda3/envs/my_env3/lib/python3.7/site-packages/tqdm/_tqdm.py", line 1005, in __iter__
    for obj in iterable:
  File "/home/v2m/anaconda3/envs/my_env3/lib/python3.7/site-packages/mxnet/gluon/data/dataloader.py", line 450, in __next__
    batch = pickle.loads(ret.get()) if self._dataset is None else ret.get()
  File "/home/v2m/anaconda3/lib/python3.7/multiprocessing/pool.py", line 657, in get
    raise self._value
AssertionError: HybridBlock requires the first argument to forward be either Symbol or NDArray, but got <class 'PIL.Image.Image'>
```

Here is my tested command line:

```
CUDA_VISIBLE_DEVICES=0 python test.py --dataset citys --model-zoo psp_resnet101_citys --ngpus 1 --test-batch-size 8
```

I downloaded the test.py script from here: https://gluon-cv.mxnet.io/_downloads/c0c97e4de5dee6fb6657817466f33994/test.py. Thank you

**Comment by dgks0n** [comment]
I found a solution to solve this issue.
