### ISSUE TITLE
MixSoftmaxCrossEntropyOHEMLoss not work

### ISSUE THREAD

**Issue by tianye2856** [dmlc/gluon-cv#890]
I try your train example in https://gluon-cv.mxnet.io/build/examples_segmentation/train_psp.html and it works well on both Mac and Linux GPU server. 
But when I change the loss function from MixSoftmaxCrossEntropyLoss to MixSoftmaxCrossEntropyOHEMLoss, it always show me the error below.
It seems that your example only support softmax cross entropy loss, all other loss are not supported like Focal loss or OHEM loss.
Is there any way to fix this problem? I have kept searching on the Internet for about 3 days and did not find any solution.
Thanks in advance.

Training images: 20210
Traceback (most recent call last):
  File "/Users/danieltian/Desktop/Code/deeplearning/PSPNet_ADE20K/train_psp_cpu_demo.py", line 203, in <module>
    losses = criterion(outputs, target)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/gluoncv/utils/parallel.py", line 100, in __call__
    return tuple_map(self.module(*(inputs[0] + targets[0]), **kwargs[0]))
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/mxnet/gluon/block.py", line 540, in __call__
    out = self.forward(*args)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/mxnet/gluon/block.py", line 917, in forward
    return self.hybrid_forward(ndarray, x, *args, **params)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/gluoncv/loss.py", line 418, in hybrid_forward
    return self._aux_forward(F, *inputs, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/gluoncv/loss.py", line 410, in _aux_forward
    hybrid_forward(F, pred1, label, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/gluoncv/loss.py", line 379, in hybrid_forward
    softmaxout = F.contrib.SoftmaxOHEMOutput(
AttributeError: module 'mxnet.ndarray.contrib' has no attribute 'SoftmaxOHEMOutput'

**Comment by tianye2856** [comment]
Can anyone help me?

**Comment by zhanghang1989** [comment]
That is experimental in my local repo, which is not included in mxnet.

**Comment by hetong007** [comment]
@zhanghang1989 would you consider it as a fix-able issue?

**Comment by zhanghang1989** [comment]
Probably removing `SoftmaxOHEMOutput` from gluoncv, as I am not actively working on CV problems.
