### ISSUE TITLE
Mask RCNN training: IndexError: list index out of range 

### ISSUE THREAD

**Issue by YuhanLiu11** [dmlc/gluon-cv#892]
Hi,

I am using mxnet 1.5.0 cuda version and gluoncv 0.3, and trying to use my own dataset in coco format to train Mask RCNN. I changed the classes in gluon/gluoncv/utils/metrics/coco_instance.py as my own classes, and used net.reset_class to set my classes as mentioned in #716 . However, I encountered an error:

/srv/home/yliu/mxnet4/gluon/gluoncv/utils/metrics/coco_instance.py:78: UserWarning: Recorded 0 out of 1 validation images, incomplete results
  self._current_id, len(self._img_ids)))
/srv/home/yliu/mxnet4/datamask_rcnn_resnet50_v1b_coco_eval_2019_08_02_14_37_12.json
Loading and preparing results...
Traceback (most recent call last):
  File "train_mask_rcnn.py", line 531, in <module>
    train_dataset, val_dataset, eval_metric = get_dataset("defect", args)
  File "train_mask_rcnn.py", line 239, in get_dataset
    print(val_metric)
  File "/srv/home/yliu/anaconda3/envs/mxnetcpu/lib/python3.6/site-packages/mxnet/metric.py", line 98, in __str__
    return "EvalMetric: {}".format(dict(self.get_name_value()))
  File "/srv/home/yliu/anaconda3/envs/mxnetcpu/lib/python3.6/site-packages/mxnet/metric.py", line 202, in get_name_value
    name, value = self.get()
  File "/srv/home/yliu/mxnet4/gluon/gluoncv/utils/metrics/coco_instance.py", line 134, in get
    bbox_names, bbox_values = self._update('bbox')
  File "/srv/home/yliu/mxnet4/gluon/gluoncv/utils/metrics/coco_instance.py", line 110, in _update
    pred = self.dataset.coco.loadRes(self._filename)
  File "/srv/home/yliu/.local/lib/python3.6/site-packages/pycocotools/coco.py", line 318, in loadRes
    if 'caption' in anns[0]:
IndexError: list index out of range

I think I have successfully loaded the json because I printed the length of items, labels and segms in _load_jsons function in gluon/gluoncv/data/mscoco/instance.py and it's the number of images I have. 

Does anyone know what the problem is?

Thanks a lot!

**Comment by Jerryzcn** [comment]
The evaluation was not run correctly, and thus the json file is incomplete.
see `UserWarning: Recorded 0 out of 1 validation images, incomplete results`
Maybe the validation data are not loaded correctly? Can you check if your validation image and label are loaded correctly in the memory?

**Comment by YuhanLiu11** [comment]
Thanks a lot for your help. It looks like I printed the val_metric before the validation process begins which causes the error. If I do not print val_metric there, I can start training using my own dataset.
