### ISSUE TITLE
Can't train mask RCNN with AMP enabled

### ISSUE THREAD

**Issue by larroy** [dmlc/gluon-cv#962]
I'm using: `pip install mxnet-cu101` and gluon-cv from master.

When trying to train mask RCNN with multiple GPU there's no progress. Without amp seems to work. static-alloc doesn't make a difference.

@Kh4L 

```
(py3) piotr@ip-172-31-6-74:0: ~/g/s/i/mask_rcnn [master]> python train_mask_rcnn.py --gpus 0,1,2,3,4,5,6,7 --dataset coco --amp --log-interval 100 --static-alloc 2>&1 | tee mask_rnn_coco_amp.log
loading annotations into memory...
Done (t=11.26s)
creating index...
index created!
loading annotations into memory...
Done (t=0.32s)
creating index...
index created!
/home/piotr/py3/lib/python3.6/site-packages/mxnet/gluon/parameter.py:678: UserWarning: Constant parameter "maskrcnn0_rpn0_rpnanchorgenerator0_anchor_" does not support grad_req other than "null", and new value "write" is ignored.
  'is ignored.'.format(self.name, req))
INFO:root:Namespace(amp=True, batch_size=8, dataset='coco', disable_hybridization=False, epochs=26, executor_threads=1, gpus='0,1,2,3,4,5,6,7', horovod=False, kv_store='nccl', log_interval=100, lr=0.01, lr_decay=0.1, lr_decay_epoch='17,23', lr_warmup=1000, lr_warmup_factor=0.3333333333333333, momentum=0.9, network='resnet50_v1b', norm_layer=None, num_workers=4, resume='', save_interval=1, save_prefix='mask_rcnn_resnet50_v1b_coco', seed=233, start_epoch=0, static_alloc=True, use_fpn=False, val_interval=1, verbose=False, wd=0.0001)
INFO:root:Start training from [Epoch 0]
INFO:root:[Epoch 0 Iteration 0] Set learning rate to 0.003333333333333333


```

**Comment by larroy** [comment]
`gdb (which python) 47928 -ex 'set confirm off' -ex 'thr apply all bt' -ex 'quit'`


[bt.txt](https://github.com/dmlc/gluon-cv/files/3666145/bt.txt)

**Comment by larroy** [comment]
Single gpu seems stuck as well:

```
(py3) piotr@ip-172-31-6-74:130: ~/g/s/d/faster_rcnn [master]> python train_faster_rcnn.py --dataset coco -j 4 --log-interval 10 --amp 2>&1 | tee faster_rcnn_amp.log
loading annotations into memory...
Done (t=11.31s)
creating index...
index created!
loading annotations into memory...
Done (t=0.32s)
creating index...
index created!
/home/piotr/py3/lib/python3.6/site-packages/mxnet/gluon/parameter.py:678: UserWarning: Constant parameter "fasterrcnn0_rpn0_rpnanchorgenerator0_anchor_" does not support grad_req other than "null", and new value "write" is ignored.
  'is ignored.'.format(self.name, req))
INFO:root:Namespace(amp=True, batch_size=8, dataset='coco', disable_hybridization=False, epochs=26, executor_threads=1, gpus='0', horovod=False, kv_store='nccl', log_interval=10, lr=0.01, lr_decay=0.1, lr_decay_epoch='17,23', lr_warmup=1000, lr_warmup_factor=0.3333333333333333, mixup=False, momentum=0.9, network='resnet50_v1b', no_mixup_epochs=20, norm_layer=None, num_workers=4, resume='', save_interval=1, save_prefix='faster_rcnn_resnet50_v1b_coco', seed=233, start_epoch=0, static_alloc=False, use_fpn=False, val_interval=1, verbose=False, wd=0.0001)
INFO:root:Start training from [Epoch 0]
INFO:root:[Epoch 0 Iteration 0] Set learning rate to 0.003333333333333333

```

**Comment by Kh4L** [comment]
So I believe this is related to #959

**Comment by larroy** [comment]
```
[1,4]<stderr>:INFO:root:[Epoch 0 Iteration 900] Set learning rate to 0.009333333333333334
[1,6]<stderr>:Traceback (most recent call last):
[1,6]<stderr>:  File "train_mask_rcnn.py", line 494, in <module>
[1,6]<stderr>:    train(net, train_data, val_data, eval_metric, batch_size, ctx, args)
[1,6]<stderr>:  File "train_mask_rcnn.py", line 392, in train
[1,6]<stderr>:    for i, batch in enumerate(train_data):
[1,6]<stderr>:  File "/home/piotr/py3/lib/python3.6/site-packages/mxnet/gluon/data/dataloader.py", line 451, in __next__
[1,6]<stderr>:    batch = pickle.loads(ret.get()) if self._dataset is None else ret.get()
[1,6]<stderr>:  File "/home/piotr/py3/lib/python3.6/site-packages/mxnet/gluon/data/dataloader.py", line 57, in rebuild_ndarray
[1,6]<stderr>:    fd = fd.detach()
[1,6]<stderr>:  File "/usr/lib/python3.6/multiprocessing/resource_sharer.py", line 58, in detach
[1,6]<stderr>:    return reduction.recv_handle(conn)
[1,6]<stderr>:  File "/usr/lib/python3.6/multiprocessing/reduction.py", line 182, in recv_handle
[1,6]<stderr>:    return recvfds(s, 1)[0]
[1,6]<stderr>:  File "/usr/lib/python3.6/multiprocessing/reduction.py", line 161, in recvfds
[1,6]<stderr>:    len(ancdata))
[1,6]<stderr>:RuntimeError: received 0 items of ancdata
[1,0]<stderr>:Traceback (most recent call last):
[1,0]<stderr>:  File "train_mask_rcnn.py", line 494, in <module>
[1,0]<stderr>:    train(net, train_data, val_data, eval_metric, batch_size, ctx, args)
[1,0]<stderr>:  File "train_mask_rcnn.py", line 419, in train
[1,0]<stderr>:    metric.update(0, record)
[1,0]<stderr>:  File "/home/piotr/py3/lib/python3.6/site-packages/mxnet/metric.py", line 1636, in update
[1,0]<stderr>:    loss = ndarray.sum(pred).asscalar()
[1,0]<stderr>:  File "/home/piotr/py3/lib/python3.6/site-packages/mxnet/ndarray/ndarray.py", line 2014, in asscalar
[1,0]<stderr>:    return self.asnumpy()[0]
[1,0]<stderr>:  File "/home/piotr/py3/lib/python3.6/site-packages/mxnet/ndarray/ndarray.py", line 1996, in asnumpy
[1,0]<stderr>:    ctypes.c_size_t(data.size)))
[1,0]<stderr>:  File "/home/piotr/py3/lib/python3.6/site-packages/mxnet/base.py", line 253, in check_call
[1,0]<stderr>:    raise MXNetError(py_str(_LIB.MXGetLastError()))
[1,0]<stderr>:mxnet.base.MXNetError: Horovod has been shut down. This was caused by an exception on one of the ranks or an attempt to allreduce, allgather or broadcast a tensor after one of the ranks finished execution. If the shutdown was caused by an exception, you should see the exception in the log before the first shutdown message.
[1,5]<stderr>:INFO:root:[Epoch 0 Iteration 900] Set learning rate to 0.009333333333333334
[1,3]<stderr>:INFO:root:[Epoch 0 Iteration 1000] Set learning rate to 0.01
[1,4]<stderr>:INFO:root:[Epoch 0 Iteration 1000] Set learning rate to 0.01
[1,1]<stderr>:INFO:root:[Epoch 0 Iteration 1000] Set learning rate to 0.01
[1,2]<stderr>:INFO:root:[Epoch 0 Iteration 1000] Set learning rate to 0.01
[1,7]<stderr>:INFO:root:[Epoch 0 Iteration 1000] Set learning rate to 0.01
[1,5]<stderr>:INFO:root:[Epoch 0 Iteration 1000] Set learning rate to 0.01
--------------------------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
mpirun detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[23939,1],0]
  Exit code:    1
--------------------------------------------------------------------------
Command exited with non-zero status 1
1195.18user 40.13system 3:06.28elapsed 663%CPU (0avgtext+0avgdata 6467216maxresident)k
0inputs+16904outputs (7major+8567939minor)pagefaults 0swaps
(py3) piotr@ip-172-31-6-74:0: ~/g/s/i/mask_rcnn [master]> time horovodrun -np 8 -H localhost:8 python train_mask_rcnn.py --dataset coco -j 16 --log-interval 100 --horovod --static-alloc --kv-store device  2>&1 | tee mrcnn_horovod_no_amp.log
```

**Comment by Jerryzcn** [comment]
have you tried ```--kv-store device```

**Comment by larroy** [comment]
with --kv-store device seems to work. Do you know the root cause?

**Comment by Jerryzcn** [comment]
@larroy the current default is actually nccl. amp is not implemented for nccl i think.

**Comment by larroy** [comment]
With single gpu also gets stuck:

```
(py3) piotr@ip-172-31-6-74:130: ~/g/s/i/mask_rcnn [master]> python train_mask_rcnn.py --gpus 0 --dataset coco --amp --log-interval 10 --static-alloc --kv-store device 2>&1 | tee  train.log
loading annotations into memory...
Done (t=11.32s)
creating index...
index created!
loading annotations into memory...
Done (t=0.32s)
creating index...
index created!
/home/piotr/py3/lib/python3.6/site-packages/mxnet/gluon/parameter.py:678: UserWarning: Constant parameter "maskrcnn0_rpn0_rpnanchorgenerator0_anchor_" does not support grad_req other than "null", and new value "write" is ignored.
  'is ignored.'.format(self.name, req))
INFO:root:Namespace(amp=True, batch_size=8, dataset='coco', disable_hybridization=False, epochs=26, executor_threads=1, gpus='0', horovod=False, kv_store='device', log_interval=10, lr=0.01, lr_decay=0.1, lr_decay_epoch='17,23', lr_warmup=1000, lr_warmup_factor=0.3333333333333333, momentum=0.9, network='resnet50_v1b', norm_layer=None, num_workers=4, resume='', save_interval=1, save_prefix='mask_rcnn_resnet50_v1b_coco', seed=233, start_epoch=0, static_alloc=True, use_fpn=False, val_interval=1, verbose=False, wd=0.0001)
INFO:root:Start training from [Epoch 0]
INFO:root:[Epoch 0 Iteration 0] Set learning rate to 0.003333333333333333
INFO:root:AMP: decreasing loss scale to 32768.000000
INFO:root:AMP: decreasing loss scale to 16384.000000
INFO:root:AMP: decreasing loss scale to 8192.000000
INFO:root:AMP: decreasing loss scale to 4096.000000
INFO:root:AMP: decreasing loss scale to 2048.000000
```

**Comment by djaym7** [comment]
Same problem, mine is stuck at validation/ after epoch 0,1

**Comment by djaym7** [comment]
NFO:root:[Epoch 0 Iteration 200] Set learning rate to 0.00043749999999999995
INFO:root:[Epoch 0] Training cost: 44.223, RPN_Conf=0.359,RPN_SmoothL1=0.046,RCNN_CrossEntropy=0.629,RCNN_SmoothL1=0.390,RCNN_Mask=0.419
/home/ec2-user/anaconda3/envs/mxnet_p36/lib/python3.6/site-packages/mxnet/gluon/block.py:758: UserWarning: Parameter maskrcnn0_normalizedperclassboxcenterencoder0_stds, maskrcnn0_normalizedperclassboxcenterencoder0_means is not used by any computation. Is this intended?
  out = self.forward(*args)


Gets stuck here @zhreshold

**Comment by djaym7** [comment]
!python train_mask_rcnn.py --gpus 1 --dataset-root '../Footprint/data/footprint-rectified/' --train-split-name instances_train --val-split-name instances_val --batch-size 1 --epochs 30 --save-prefix "./model/" --log-interval 10
