### ISSUE TITLE
runtime error in Mask rcnn training with horovod 

### ISSUE THREAD

**Issue by larroy** [dmlc/gluon-cv#970]
While training on a p3dn.24 with horovod, I get an error after the first epoch:

```
horovodrun -np 8 -H localhost:8 python train_faster_rcnn.py --dataset coco -j 4 --log-interval 100 --amp --horovod 2>&1 | tee train.log
```

```
[1,0]<stderr>:INFO:root:[Epoch 0][Batch 1599], Speed: 9.490 samples/sec, RPN_Conf=0.176,RPN_SmoothL1=0.118,RCNN_CrossEntropy=0.574,RCNN_SmoothL1=0.338,RPNAcc=0.928,RPNL1Loss=0.469,RCNNAcc=0.841,RCNNL1Loss=1.604
[1,0]<stderr>:INFO:root:[Epoch 0][Batch 1699], Speed: 9.792 samples/sec, RPN_Conf=0.174,RPN_SmoothL1=0.118,RCNN_CrossEntropy=0.567,RCNN_SmoothL1=0.334,RPNAcc=0.929,RPNL1Loss=0.466,RCNNAcc=0.842,RCNNL1Loss=1.583
[1,0]<stderr>:INFO:root:[Epoch 0][Batch 1799], Speed: 9.739 samples/sec, RPN_Conf=0.171,RPN_SmoothL1=0.117,RCNN_CrossEntropy=0.559,RCNN_SmoothL1=0.331,RPNAcc=0.930,RPNL1Loss=0.465,RCNNAcc=0.843,RCNNL1Loss=1.564
[1,0]<stderr>:INFO:root:[Epoch 0] Training cost: 1506.709, RPN_Conf=0.171,RPN_SmoothL1=0.117,RCNN_CrossEntropy=0.557,RCNN_SmoothL1=0.330
[1,4]<stderr>:Traceback (most recent call last):
[1,4]<stderr>:  File "train_faster_rcnn.py", line 502, in <module>
[1,4]<stderr>:    train(net, train_data, val_data, eval_metric, batch_size, ctx, args)
[1,4]<stderr>:  File "train_faster_rcnn.py", line 451, in train
[1,4]<stderr>:    executor.__del__()
[1,4]<stderr>:AttributeError: 'NoneType' object has no attribute '__del__'
[1,7]<stderr>:Traceback (most recent call last):
[1,7]<stderr>:  File "train_faster_rcnn.py", line 502, in <module>
[1,7]<stderr>:    train(net, train_data, val_data, eval_metric, batch_size, ctx, args)
[1,7]<stderr>:  File "train_faster_rcnn.py", line 451, in train
[1,7]<stderr>:    executor.__del__()
[1,7]<stderr>:AttributeError: 'NoneType' object has no attribute '__del__'
[1,2]<stderr>:Traceback (most recent call last):
[1,2]<stderr>:  File "train_faster_rcnn.py", line 502, in <module>
[1,2]<stderr>:    train(net, train_data, val_data, eval_metric, batch_size, ctx, args)
[1,2]<stderr>:  File "train_faster_rcnn.py", line 451, in train
[1,2]<stderr>:    executor.__del__()
[1,2]<stderr>:AttributeError: 'NoneType' object has no attribute '__del__'
[1,3]<stderr>:Traceback (most recent call last):
[1,3]<stderr>:  File "train_faster_rcnn.py", line 502, in <module>
[1,3]<stderr>:    train(net, train_data, val_data, eval_metric, batch_size, ctx, args)
[1,3]<stderr>:  File "train_faster_rcnn.py", line 451, in train
[1,3]<stderr>:    executor.__del__()
[1,3]<stderr>:AttributeError: 'NoneType' object has no attribute '__del__'
[1,1]<stderr>:Traceback (most recent call last):
[1,1]<stderr>:  File "train_faster_rcnn.py", line 502, in <module>
[1,1]<stderr>:    train(net, train_data, val_data, eval_metric, batch_size, ctx, args)
[1,1]<stderr>:  File "train_faster_rcnn.py", line 451, in train
[1,1]<stderr>:    executor.__del__()
[1,1]<stderr>:AttributeError: 'NoneType' object has no attribute '__del__'
[1,6]<stderr>:Traceback (most recent call last):
[1,6]<stderr>:  File "train_faster_rcnn.py", line 502, in <module>
[1,6]<stderr>:    train(net, train_data, val_data, eval_metric, batch_size, ctx, args)
[1,6]<stderr>:  File "train_faster_rcnn.py", line 451, in train
[1,6]<stderr>:    executor.__del__()
[1,6]<stderr>:AttributeError: 'NoneType' object has no attribute '__del__'
[1,5]<stderr>:Traceback (most recent call last):
[1,5]<stderr>:  File "train_faster_rcnn.py", line 502, in <module>
[1,5]<stderr>:    train(net, train_data, val_data, eval_metric, batch_size, ctx, args)
[1,5]<stderr>:  File "train_faster_rcnn.py", line 451, in train
[1,5]<stderr>:    executor.__del__()
[1,5]<stderr>:AttributeError: 'NoneType' object has no attribute '__del__'
--------------------------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
mpirun detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[53969,1],7]
  Exit code:    1
--------------------------------------------------------------------------
```

**Comment by zhreshold** [comment]
@Jerryzcn @Kh4L any clue?

**Comment by larroy** [comment]
@apeforest said that exception is not propagated well from Horovod...

**Comment by Jerryzcn** [comment]
You can remove `executor.__del__()`
